In [122]:
import sys
!{sys.executable} -m pip install spotipy

Requirement already satisfied: spotipy in /opt/anaconda3/lib/python3.11/site-packages (2.25.2)
Requirement already satisfied: redis>=3.5.3 in /opt/anaconda3/lib/python3.11/site-packages (from spotipy) (7.1.1)
Requirement already satisfied: requests>=2.25.0 in /opt/anaconda3/lib/python3.11/site-packages (from spotipy) (2.31.0)
Requirement already satisfied: urllib3>=1.26.0 in /opt/anaconda3/lib/python3.11/site-packages (from spotipy) (2.0.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.11/site-packages (from requests>=2.25.0->spotipy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.11/site-packages (from requests>=2.25.0->spotipy) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.11/site-packages (from requests>=2.25.0->spotipy) (2025.1.31)

In [123]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import pandas as pd

In [126]:
#add your keys here
client_credentials_manager = SpotifyClientCredentials(client_id="", client_secret="")

In [128]:
sp = spotipy.Spotify(client_credentials_manager = client_credentials_manager)

In [130]:
playlist_link = "https://open.spotify.com/playlist/5gkDZIXRY0bfrh3xqZU7M3"

In [132]:
playlist_link

'https://open.spotify.com/playlist/5gkDZIXRY0bfrh3xqZU7M3'

In [136]:
playlist_link.split("/")

['https:', '', 'open.spotify.com', 'playlist', '5gkDZIXRY0bfrh3xqZU7M3']

In [138]:
playlist_link.split("/")[-1]#.split('?')[0]

'5gkDZIXRY0bfrh3xqZU7M3'

In [242]:
playlist_link.split("/")[-1].split('?')

['5gkDZIXRY0bfrh3xqZU7M3']

In [244]:
playlist_link.split("/")[-1].split('?')[0]

'5gkDZIXRY0bfrh3xqZU7M3'

In [142]:
playlist_URI = playlist_link.split("/")[-1].split('?')[0]

In [144]:
data = sp.playlist_tracks(playlist_URI)

In [146]:
data

{'href': 'https://api.spotify.com/v1/playlists/5gkDZIXRY0bfrh3xqZU7M3/tracks?offset=0&limit=100&additional_types=track',
 'items': [{'added_at': '2018-09-20T16:07:04Z',
   'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/evebvb6vpgyn9xtip57ou6087'},
    'href': 'https://api.spotify.com/v1/users/evebvb6vpgyn9xtip57ou6087',
    'id': 'evebvb6vpgyn9xtip57ou6087',
    'type': 'user',
    'uri': 'spotify:user:evebvb6vpgyn9xtip57ou6087'},
   'is_local': False,
   'primary_color': None,
   'track': {'preview_url': None,
    'available_markets': ['AR',
     'AU',
     'AT',
     'BE',
     'BO',
     'BR',
     'BG',
     'CA',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DK',
     'DO',
     'DE',
     'EC',
     'EE',
     'SV',
     'FI',
     'FR',
     'GR',
     'GT',
     'HN',
     'HK',
     'HU',
     'IS',
     'IE',
     'IT',
     'LV',
     'LT',
     'LU',
     'MY',
     'MT',
     'MX',
     'NL',
     'NZ',
     'NI',
     'NO',
     'PA',
     'PY',
     'PE',
     'PH',
     'PL',
     'PT',
     'SG',
     'SK',
     'ES',
     'SE',
     'CH',
     'TW',
     'TR',
     'UY',
     'US',
     'GB',
     'AD',
     'LI',
     'MC',
     'ID',
     'JP',
     'TH',
     'VN',
     'RO',
     'IL',
     'ZA',
     'SA',
     'AE',
     'BH',
     'QA',
     'OM',
     'KW',
     'EG',
     'MA',
     'DZ',
     'TN',
     'LB',
     'JO',
     'PS',
     'IN',
     'KZ',
     'MD',
     'UA',
     'AL',
     'BA',
     'HR',
     'ME',
     'MK',
     'RS',
     'SI',
     'KR',
     'BD',
     'PK',
     'LK',
     'GH',
     'KE',
     'NG',
     'TZ',
     'UG',
     'AG',
     'AM',
     'BS',
     'BB',
     'BZ',
     'BT',
     'BW',
     'CV',
     'CW',
     'DM',
     'FJ',
     'GM',
     'GE',
     'GD',
     'GW',
     'GY',
     'HT',
     'JM',
     'KI',
     'LS',
     'LR',
     'MW',
     'MV',
     'ML',
     'MH',
     'FM',
     'NA',
     'NR',
     'NE',
     'PW',
     'PG',
     'WS',
     'SM',
     'ST',
     'SN',
     'SC',
     'SL',
     'SB',
     'KN',
     'LC',
     'VC',
     'SR',
     'TL',
     'TO',
     'TT',
     'TV',
     'VU',
     'AZ',
     'BI',
     'KH',
     'CM',
     'TD',
     'KM',
     'GQ',
     'SZ',
     'GA',
     'GN',
     'KG',
     'LA',
     'MO',
     'MR',
     'MN',
     'RW',
     'TG',
     'ZW',
     'BJ',
     'MG',
     'MU',
     'MZ',
     'AO',
     'CI',
     'DJ',
     'ZM',
     'CD',
     'CG',
     'IQ',
     'LY',
     'TJ',
     'VE',
     'ET',
     'XK'],
    'explicit': True,
    'type': 'track',
    'episode': False,
    'track': True,
    'album': {'available_markets': ['AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
      'JP',
      'TH',
      'VN',
      'RO',
      'IL',
      'ZA',
      'SA',
      'AE',
      'BH',
      'QA',
      'OM',
      'KW',
      'EG',
      'MA',
      'DZ',
      'TN',
      'LB',
      'JO',
      'PS',
      'IN',
      'KZ',
      'MD',
      'UA',
      'AL',
      'BA',
      'HR',
      'ME',
      'MK',
      'RS',
      'SI',
      'KR',
      'BD',
      'PK',
      'LK',
      'GH',
      'KE',
      'NG',
      'TZ',
      'UG',
      'AG',
      'AM',
      'BS',
      'BB',
      'BZ',
      'BT',
      'BW',
      'CV',
      'CW',
      'DM',
      'FJ',
      'GM',
      'GE',
      'GD',
      'GW',
      'GY',
      'HT',
      'JM',
      'KI',
      'LS',
      'LR',
      'MW',
      'MV',
      'ML',
      'MH',
      'FM',
      'NA',
      'NR',
      'NE',
      'PW',
      'PG',
      'WS',
      'SM',
      'ST',
      'SN',
      'SC',
      'SL',
      'SB',
      'KN',
      'LC',
      'VC',
      'SR',
      'TL',
      'TO',
      'TT',
      'TV',
      'VU',
      'AZ',
      'BI',
      'KH',
      'CM',
      'TD',
      'KM',
      'GQ',
      'SZ',
      'GA',
      'GN',
      'KG',
      'LA',
      'MO',
      'MR',
      'MN',
      'RW',
      'TG',
      'ZW',
      'BJ',
      'MG',
      'MU',
      'MZ',
      'AO',
      'CI',
      'DJ',
      'ZM',
      'CD',
      'CG',
      'IQ',
      'LY',
      'TJ',
      'VE',
      'ET',
      'XK'],
     'type': 'album',
     'album_type': 'single',
     'href': 'https://api.spotify.com/v1/albums/185Tm1g5U7eMOrm3m9SQUh',
     'id': '185Tm1g5U7eMOrm3m9SQUh',
     'images': [{'height': 640,
       'url': 'https://i.scdn.co/image/ab67616d0000b273b6d544387b04e1d1a5f7926c',
       'width': 640},
      {'height': 300,
       'url': 'https://i.scdn.co/image/ab67616d00001e02b6d544387b04e1d1a5f7926c',
       'width': 300},
      {'height': 64,
       'url': 'https://i.scdn.co/image/ab67616d00004851b6d544387b04e1d1a5f7926c',
       'width': 64}],
     'name': 'I Love It',
     'release_date': '2018-09-07',
     'release_date_precision': 'day',
     'uri': 'spotify:album:185Tm1g5U7eMOrm3m9SQUh',
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x'},
       'href': 'https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x',
       'id': '5K4W6rqBFWDnAN6FQUkS6x',
       'name': 'Kanye West',
       'type': 'artist',
       'uri': 'spotify:artist:5K4W6rqBFWDnAN6FQUkS6x'},
      {'external_urls': {'spotify': 'https://open.spotify.com/artist/3wyVrVrFCkukjdVIdirGVY'},
       'href': 'https://api.spotify.com/v1/artists/3wyVrVrFCkukjdVIdirGVY',
       'id': '3wyVrVrFCkukjdVIdirGVY',
       'name': 'Lil Pump',
       'type': 'artist',
       'uri': 'spotify:artist:3wyVrVrFCkukjdVIdirGVY'}],
     'external_urls': {'spotify': 'https://open.spotify.com/album/185Tm1g5U7eMOrm3m9SQUh'},
     'total_tracks': 1},
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x'},
      'href': 'https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x',
      'id': '5K4W6rqBFWDnAN6FQUkS6x',
      'name': 'Kanye West',
      'type': 'artist',
      'uri': 'spotify:artist:5K4W6rqBFWDnAN6FQUkS6x'},
     {'external_urls': {'spotify': 'https://open.spotify.com/artist/3wyVrVrFCkukjdVIdirGVY'},
      'href': 'https://api.spotify.com/v1/artists/3wyVrVrFCkukjdVIdirGVY',
      'id': '3wyVrVrFCkukjdVIdirGVY',
      'name': 'Lil Pump',
      'type': 'artist',
      'uri': 'spotify:artist:3wyVrVrFCkukjdVIdirGVY'}],
    'disc_number': 1,
    'track_number': 1,
    'duration_ms': 127946,
    'external_ids': {'isrc': 'USUM71814031'},
    'external_urls': {'spotify': 'https://open.spotify.com/track/4S8d14HvHb70ImctNgVzQQ'},
    'href': 'https://api.spotify.com/v1/tracks/4S8d14HvHb70ImctNgVzQQ',
    'id': '4S8d14HvHb70ImctNgVzQQ',
    'name': 'I Love It (& Lil Pump)',
    'popularity': 69,
    'uri': 'spotify:track:4S8d14HvHb70ImctNgVzQQ',
    'is_local': False},
   'video_thumbnail': {'url': None}},
  {'added_at': '2018-09-20T16:07:04Z',
   'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/evebvb6vpgyn9xtip57ou6087'},
    'href': 'https://api.spotify.com/v1/users/evebvb6vpgyn9xtip57ou6087',
    'id': 'evebvb6vpgyn9xtip57ou6087',
    'type': 'user',
    'uri': 'spotify:user:evebvb6vpgyn9xtip57ou6087'},
   'is_local': False,
   'primary_color': None,
   'track': {'preview_url': None,
    'available_markets': ['AR',
     'AU',
     'AT',
     'BE',
     'BO',
     'BR',
     'BG',
     'CA',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DK',
     'DO',
     'DE',
     'EC',
     'EE',
     'SV',
     'FI',
     'FR',
     'GR',
     'GT',
     'HN',
     'HK',
     'HU',
     'IS',
     'IE',
     'IT',
     'LV',
     'LT',
     'LU',
     'MY',
     'MT',
     'MX',
     'NL',
     'NZ',
     'NI',
     'NO',
     'PA',
     'PY',
     'PE',
     'PH',
     'PL',
     'PT',
     'SG',
     'SK',
     'ES',
     'SE',
     'CH',
     'TW',
     'TR',
     'UY',
     'US',
     'GB',
     'AD',
     'LI',
     'MC',
     'ID',
     'JP',
     'TH',
     'VN',
     'RO',
     'IL',
     'ZA',
     'SA',
     'AE',
     'BH',
     'QA',
     'OM',
     'KW',
     'EG',
     'MA',
     'DZ',
     'TN',
     'LB',
     'JO',
     'PS',
     'IN',
     'KZ',
     'MD',
     'UA',
     'AL',
     'BA',
     'HR',
     'ME',
     'MK',
     'RS',
     'SI',
     'KR',
     'BD',
     'PK',
     'LK',
     'GH',
     'KE',
     'NG',
     'TZ',
     'UG',
     'AG',
     'AM',
     'BS',
     'BB',
     'BZ',
     'BT',
     'BW',
     'BF',
     'CV',
     'CW',
     'DM',
     'FJ',
     'GM',
     'GE',
     'GD',
     'GW',
     'GY',
     'HT',
     'JM',
     'KI',
     'LS',
     'LR',
     'MW',
     'MV',
     'ML',
     'MH',
     'FM',
     'NA',
     'NR',
     'NE',
     'PW',
     'PG',
     'WS',
     'SM',
     'ST',
     'SN',
     'SC',
     'SL',
     'SB',
     'KN',
     'LC',
     'VC',
     'SR',
     'TL',
     'TO',
     'TT',
     'TV',
     'VU',
     'AZ',
     'BN',
     'BI',
     'KH',
     'CM',
     'TD',
     'KM',
     'GQ',
     'SZ',
     'GA',
     'GN',
     'KG',
     'LA',
     'MO',
     'MR',
     'MN',
     'NP',
     'RW',
     'TG',
     'UZ',
     'ZW',
     'BJ',
     'MG',
     'MU',
     'MZ',
     'AO',
     'CI',
     'DJ',
     'ZM',
     'CD',
     'CG',
     'IQ',
     'LY',
     'TJ',
     'VE',
     'ET',
     'XK'],
    'explicit': True,
    'type': 'track',
    'episode': False,
    'track': True,
    'album': {'available_markets': ['AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
      'JP',
      'TH',
      'VN',
      'RO',
      'IL',
      'ZA',
      'SA',
      'AE',
      'BH',
      'QA',
      'OM',
      'KW',
      'EG',
      'MA',
      'DZ',
      'TN',
      'LB',
      'JO',
      'PS',
      'IN',
      'KZ',
      'MD',
      'UA',
      'AL',
      'BA',
      'HR',
      'ME',
      'MK',
      'RS',
      'SI',
      'KR',
      'BD',
      'PK',
      'LK',
      'GH',
      'KE',
      'NG',
      'TZ',
      'UG',
      'AG',
      'AM',
      'BS',
      'BB',
      'BZ',
      'BT',
      'BW',
      'BF',
      'CV',
      'CW',
      'DM',
      'FJ',
      'GM',
      'GE',
      'GD',
      'GW',
      'GY',
      'HT',
      'JM',
      'KI',
      'LS',
      'LR',
      'MW',
      'MV',
      'ML',
      'MH',
      'FM',
      'NA',
      'NR',
      'NE',
      'PW',
      'PG',
      'WS',
      'SM',
      'ST',
      'SN',
      'SC',
      'SL',
      'SB',
      'KN',
      'LC',
      'VC',
      'SR',
      'TL',
      'TO',
      'TT',
      'TV',
      'VU',
      'AZ',
      'BN',
      'BI',
      'KH',
      'CM',
      'TD',
      'KM',
      'GQ',
      'SZ',
      'GA',
      'GN',
      'KG',
      'LA',
      'MO',
      'MR',
      'MN',
      'NP',
      'RW',
      'TG',
      'UZ',
      'ZW',
      'BJ',
      'MG',
      'MU',
      'MZ',
      'AO',
      'CI',
      'DJ',
      'ZM',
      'CD',
      'CG',
      'IQ',
      'LY',
      'TJ',
      'VE',
      'ET',
      'XK'],
     'type': 'album',
     'album_type': 'album',
     'href': 'https://api.spotify.com/v1/albums/3HNnxK7NgLXbDoxRZxNWiR',
     'id': '3HNnxK7NgLXbDoxRZxNWiR',
     'images': [{'height': 640,
       'url': 'https://i.scdn.co/image/ab67616d0000b273e4073def0c03a91e3fceaf73',
       'width': 640},
      {'height': 300,
       'url': 'https://i.scdn.co/image/ab67616d00001e02e4073def0c03a91e3fceaf73',
       'width': 300},
      {'height': 64,
       'url': 'https://i.scdn.co/image/ab67616d00004851e4073def0c03a91e3fceaf73',
       'width': 64}],
     'name': 'Kamikaze',
     'release_date': '2018-08-31',
     'release_date_precision': 'day',
     'uri': 'spotify:album:3HNnxK7NgLXbDoxRZxNWiR',
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR'},
       'href': 'https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR',
       'id': '7dGJo4pcD2V6oG8kP0tJRR',
       'name': 'Eminem',
       'type': 'artist',
       'uri': 'spotify:artist:7dGJo4pcD2V6oG8kP0tJRR'}],
     'external_urls': {'spotify': 'https://open.spotify.com/album/3HNnxK7NgLXbDoxRZxNWiR'},
     'total_tracks': 13},
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR'},
      'href': 'https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR',
      'id': '7dGJo4pcD2V6oG8kP0tJRR',
      'name': 'Eminem',
      'type': 'artist',
      'uri': 'spotify:artist:7dGJo4pcD2V6oG8kP0tJRR'},
     {'external_urls': {'spotify': 'https://open.spotify.com/artist/6C1ohJrd5VydigQtaGy5Wa'},
      'href': 'https://api.spotify.com/v1/artists/6C1ohJrd5VydigQtaGy5Wa',
      'id': '6C1ohJrd5VydigQtaGy5Wa',
      'name': 'Joyner Lucas',
      'type': 'artist',
      'uri': 'spotify:artist:6C1ohJrd5VydigQtaGy5Wa'}],
    'disc_number': 1,
    'track_number': 3,
    'duration_ms': 244679,
    'external_ids': {'isrc': 'USUM71813334'},
    'external_urls': {'spotify': 'https://open.spotify.com/track/60SdxE8apGAxMiRrpbmLY0'},
    'href': 'https://api.spotify.com/v1/tracks/60SdxE8apGAxMiRrpbmLY0',
    'id': '60SdxE8apGAxMiRrpbmLY0',
    'name': 'Lucky You (feat. Joyner Lucas)',
    'popularity': 70,
    'uri': 'spotify:track:60SdxE8apGAxMiRrpbmLY0',
    'is_local': False},
   'video_thumbnail': {'url': None}},
  {'added_at': '2018-09-20T16:07:04Z',
   'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/evebvb6vpgyn9xtip57ou6087'},
    'href': 'https://api.spotify.com/v1/users/evebvb6vpgyn9xtip57ou6087',
    'id': 'evebvb6vpgyn9xtip57ou6087',
    'type': 'user',
    'uri': 'spotify:user:evebvb6vpgyn9xtip57ou6087'},
   'is_local': False,
   'primary_color': None,
   'track': {'preview_url': None,
    'available_markets': ['AR',
     'AU',
     'AT',
     'BE',
     'BO',
     'BR',
     'BG',
     'CA',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DK',
     'DO',
     'DE',
     'EC',
     'EE',
     'SV',
     'FI',
     'FR',
     'GR',
     'GT',
     'HN',
     'HK',
     'HU',
     'IS',
     'IE',
     'IT',
     'LV',
     'LT',
     'LU',
     'MY',
     'MT',
     'MX',
     'NL',
     'NZ',
     'NI',
     'NO',
     'PA',
     'PY',
     'PE',
     'PH',
     'PL',
     'PT',
     'SG',
     'SK',
     'ES',
     'SE',
     'CH',
     'TW',
     'TR',
     'UY',
     'US',
     'GB',
     'AD',
     'LI',
     'MC',
     'ID',
     'JP',
     'TH',
     'VN',
     'RO',
     'IL',
     'ZA',
     'SA',
     'AE',
     'BH',
     'QA',
     'OM',
     'KW',
     'EG',
     'MA',
     'DZ',
     'TN',
     'LB',
     'JO',
     'PS',
     'IN',
     'BY',
     'KZ',
     'MD',
     'UA',
     'AL',
     'BA',
     'HR',
     'ME',
     'MK',
     'RS',
     'SI',
     'KR',
     'BD',
     'PK',
     'LK',
     'GH',
     'KE',
     'NG',
     'TZ',
     'UG',
     'AG',
     'AM',
     'BS',
     'BB',
     'BZ',
     'BT',
     'BW',
     'CV',
     'CW',
     'DM',
     'FJ',
     'GM',
     'GE',
     'GD',
     'GW',
     'GY',
     'HT',
     'JM',
     'KI',
     'LS',
     'LR',
     'MW',
     'MV',
     'ML',
     'MH',
     'FM',
     'NA',
     'NR',
     'NE',
     'PW',
     'PG',
     'WS',
     'SM',
     'ST',
     'SN',
     'SC',
     'SL',
     'SB',
     'KN',
     'LC',
     'VC',
     'SR',
     'TL',
     'TO',
     'TT',
     'TV',
     'VU',
     'AZ',
     'BI',
     'KH',
     'CM',
     'TD',
     'KM',
     'GQ',
     'SZ',
     'GA',
     'GN',
     'KG',
     'LA',
     'MO',
     'MR',
     'MN',
     'RW',
     'TG',
     'ZW',
     'BJ',
     'MG',
     'MU',
     'MZ',
     'AO',
     'CI',
     'DJ',
     'ZM',
     'CD',
     'CG',
     'IQ',
     'LY',
     'TJ',
     'VE',
     'ET',
     'XK'],
    'explicit': True,
    'type': 'track',
    'episode': False,
    'track': True,
    'album': {'available_markets': ['AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
      'JP',
      'TH',
      'VN',
      'RO',
      'IL',
      'ZA',
      'SA',
      'AE',
      'BH',
      'QA',
      'OM',
      'KW',
      'EG',
      'MA',
      'DZ',
      'TN',
      'LB',
      'JO',
      'PS',
      'IN',
      'BY',
      'KZ',
      'MD',
      'UA',
      'AL',
      'BA',
      'HR',
      'ME',
      'MK',
      'RS',
      'SI',
      'KR',
      'BD',
      'PK',
      'LK',
      'GH',
      'KE',
      'NG',
      'TZ',
      'UG',
      'AG',
      'AM',
      'BS',
      'BB',
      'BZ',
      'BT',
      'BW',
      'CV',
      'CW',
      'DM',
      'FJ',
      'GM',
      'GE',
      'GD',
      'GW',
      'GY',
      'HT',
      'JM',
      'KI',
      'LS',
      'LR',
      'MW',
      'MV',
      'ML',
      'MH',
      'FM',
      'NA',
      'NR',
      'NE',
      'PW',
      'PG',
      'WS',
      'SM',
      'ST',
      'SN',
      'SC',
      'SL',
      'SB',
      'KN',
      'LC',
      'VC',
      'SR',
      'TL',
      'TO',
      'TT',
      'TV',
      'VU',
      'AZ',
      'BI',
      'KH',
      'CM',
      'TD',
      'KM',
      'GQ',
      'SZ',
      'GA',
      'GN',
      'KG',
      'LA',
      'MO',
      'MR',
      'MN',
      'RW',
      'TG',
      'ZW',
      'BJ',
      'MG',
      'MU',
      'MZ',
      'AO',
      'CI',
      'DJ',
      'ZM',
      'CD',
      'CG',
      'IQ',
      'LY',
      'TJ',
      'VE',
      'ET',
      'XK'],
     'type': 'album',
     'album_type': 'album',
     'href': 'https://api.spotify.com/v1/albums/1ATL5GLyefJaxhQzSPVrLX',
     'id': '1ATL5GLyefJaxhQzSPVrLX',
     'images': [{'height': 640,
       'url': 'https://i.scdn.co/image/ab67616d0000b273f907de96b9a4fbc04accc0d5',
       'width': 640},
      {'height': 300,
       'url': 'https://i.scdn.co/image/ab67616d00001e02f907de96b9a4fbc04accc0d5',
       'width': 300},
      {'height': 64,
       'url': 'https://i.scdn.co/image/ab67616d00004851f907de96b9a4fbc04accc0d5',
       'width': 64}],
     'name': 'Scorpion',
     'release_date': '2018-06-29',
     'release_date_precision': 'day',
     'uri': 'spotify:album:1ATL5GLyefJaxhQzSPVrLX',
     'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3TVXtAsR1Inumwj472S9r4'},
       'href': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4',

In [147]:
data['items']

[{'added_at': '2018-09-20T16:07:04Z',
  'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/evebvb6vpgyn9xtip57ou6087'},
   'href': 'https://api.spotify.com/v1/users/evebvb6vpgyn9xtip57ou6087',
   'id': 'evebvb6vpgyn9xtip57ou6087',
   'type': 'user',
   'uri': 'spotify:user:evebvb6vpgyn9xtip57ou6087'},
  'is_local': False,
  'primary_color': None,
  'track': {'preview_url': None,
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'RW',
    'TG',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'explicit': True,
   'type': 'track',
   'episode': False,
   'track': True,
   'album': {'available_markets': ['AR',
     'AU',
     'AT',
     'BE',
     'BO',
     'BR',
     'BG',
     'CA',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DK',
     'DO',
     'DE',
     'EC',
     'EE',
     'SV',
     'FI',
     'FR',
     'GR',
     'GT',
     'HN',
     'HK',
     'HU',
     'IS',
     'IE',
     'IT',
     'LV',
     'LT',
     'LU',
     'MY',
     'MT',
     'MX',
     'NL',
     'NZ',
     'NI',
     'NO',
     'PA',
     'PY',
     'PE',
     'PH',
     'PL',
     'PT',
     'SG',
     'SK',
     'ES',
     'SE',
     'CH',
     'TW',
     'TR',
     'UY',
     'US',
     'GB',
     'AD',
     'LI',
     'MC',
     'ID',
     'JP',
     'TH',
     'VN',
     'RO',
     'IL',
     'ZA',
     'SA',
     'AE',
     'BH',
     'QA',
     'OM',
     'KW',
     'EG',
     'MA',
     'DZ',
     'TN',
     'LB',
     'JO',
     'PS',
     'IN',
     'KZ',
     'MD',
     'UA',
     'AL',
     'BA',
     'HR',
     'ME',
     'MK',
     'RS',
     'SI',
     'KR',
     'BD',
     'PK',
     'LK',
     'GH',
     'KE',
     'NG',
     'TZ',
     'UG',
     'AG',
     'AM',
     'BS',
     'BB',
     'BZ',
     'BT',
     'BW',
     'CV',
     'CW',
     'DM',
     'FJ',
     'GM',
     'GE',
     'GD',
     'GW',
     'GY',
     'HT',
     'JM',
     'KI',
     'LS',
     'LR',
     'MW',
     'MV',
     'ML',
     'MH',
     'FM',
     'NA',
     'NR',
     'NE',
     'PW',
     'PG',
     'WS',
     'SM',
     'ST',
     'SN',
     'SC',
     'SL',
     'SB',
     'KN',
     'LC',
     'VC',
     'SR',
     'TL',
     'TO',
     'TT',
     'TV',
     'VU',
     'AZ',
     'BI',
     'KH',
     'CM',
     'TD',
     'KM',
     'GQ',
     'SZ',
     'GA',
     'GN',
     'KG',
     'LA',
     'MO',
     'MR',
     'MN',
     'RW',
     'TG',
     'ZW',
     'BJ',
     'MG',
     'MU',
     'MZ',
     'AO',
     'CI',
     'DJ',
     'ZM',
     'CD',
     'CG',
     'IQ',
     'LY',
     'TJ',
     'VE',
     'ET',
     'XK'],
    'type': 'album',
    'album_type': 'single',
    'href': 'https://api.spotify.com/v1/albums/185Tm1g5U7eMOrm3m9SQUh',
    'id': '185Tm1g5U7eMOrm3m9SQUh',
    'images': [{'height': 640,
      'url': 'https://i.scdn.co/image/ab67616d0000b273b6d544387b04e1d1a5f7926c',
      'width': 640},
     {'height': 300,
      'url': 'https://i.scdn.co/image/ab67616d00001e02b6d544387b04e1d1a5f7926c',
      'width': 300},
     {'height': 64,
      'url': 'https://i.scdn.co/image/ab67616d00004851b6d544387b04e1d1a5f7926c',
      'width': 64}],
    'name': 'I Love It',
    'release_date': '2018-09-07',
    'release_date_precision': 'day',
    'uri': 'spotify:album:185Tm1g5U7eMOrm3m9SQUh',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x'},
      'href': 'https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x',
      'id': '5K4W6rqBFWDnAN6FQUkS6x',
      'name': 'Kanye West',
      'type': 'artist',
      'uri': 'spotify:artist:5K4W6rqBFWDnAN6FQUkS6x'},
     {'external_urls': {'spotify': 'https://open.spotify.com/artist/3wyVrVrFCkukjdVIdirGVY'},
      'href': 'https://api.spotify.com/v1/artists/3wyVrVrFCkukjdVIdirGVY',
      'id': '3wyVrVrFCkukjdVIdirGVY',
      'name': 'Lil Pump',
      'type': 'artist',
      'uri': 'spotify:artist:3wyVrVrFCkukjdVIdirGVY'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/185Tm1g5U7eMOrm3m9SQUh'},
    'total_tracks': 1},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x'},
     'href': 'https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x',
     'id': '5K4W6rqBFWDnAN6FQUkS6x',
     'name': 'Kanye West',
     'type': 'artist',
     'uri': 'spotify:artist:5K4W6rqBFWDnAN6FQUkS6x'},
    {'external_urls': {'spotify': 'https://open.spotify.com/artist/3wyVrVrFCkukjdVIdirGVY'},
     'href': 'https://api.spotify.com/v1/artists/3wyVrVrFCkukjdVIdirGVY',
     'id': '3wyVrVrFCkukjdVIdirGVY',
     'name': 'Lil Pump',
     'type': 'artist',
     'uri': 'spotify:artist:3wyVrVrFCkukjdVIdirGVY'}],
   'disc_number': 1,
   'track_number': 1,
   'duration_ms': 127946,
   'external_ids': {'isrc': 'USUM71814031'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/4S8d14HvHb70ImctNgVzQQ'},
   'href': 'https://api.spotify.com/v1/tracks/4S8d14HvHb70ImctNgVzQQ',
   'id': '4S8d14HvHb70ImctNgVzQQ',
   'name': 'I Love It (& Lil Pump)',
   'popularity': 69,
   'uri': 'spotify:track:4S8d14HvHb70ImctNgVzQQ',
   'is_local': False},
  'video_thumbnail': {'url': None}},
 {'added_at': '2018-09-20T16:07:04Z',
  'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/evebvb6vpgyn9xtip57ou6087'},
   'href': 'https://api.spotify.com/v1/users/evebvb6vpgyn9xtip57ou6087',
   'id': 'evebvb6vpgyn9xtip57ou6087',
   'type': 'user',
   'uri': 'spotify:user:evebvb6vpgyn9xtip57ou6087'},
  'is_local': False,
  'primary_color': None,
  'track': {'preview_url': None,
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'BF',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BN',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'NP',
    'RW',
    'TG',
    'UZ',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'explicit': True,
   'type': 'track',
   'episode': False,
   'track': True,
   'album': {'available_markets': ['AR',
     'AU',
     'AT',
     'BE',
     'BO',
     'BR',
     'BG',
     'CA',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DK',
     'DO',
     'DE',
     'EC',
     'EE',
     'SV',
     'FI',
     'FR',
     'GR',
     'GT',
     'HN',
     'HK',
     'HU',
     'IS',
     'IE',
     'IT',
     'LV',
     'LT',
     'LU',
     'MY',
     'MT',
     'MX',
     'NL',
     'NZ',
     'NI',
     'NO',
     'PA',
     'PY',
     'PE',
     'PH',
     'PL',
     'PT',
     'SG',
     'SK',
     'ES',
     'SE',
     'CH',
     'TW',
     'TR',
     'UY',
     'US',
     'GB',
     'AD',
     'LI',
     'MC',
     'ID',
     'JP',
     'TH',
     'VN',
     'RO',
     'IL',
     'ZA',
     'SA',
     'AE',
     'BH',
     'QA',
     'OM',
     'KW',
     'EG',
     'MA',
     'DZ',
     'TN',
     'LB',
     'JO',
     'PS',
     'IN',
     'KZ',
     'MD',
     'UA',
     'AL',
     'BA',
     'HR',
     'ME',
     'MK',
     'RS',
     'SI',
     'KR',
     'BD',
     'PK',
     'LK',
     'GH',
     'KE',
     'NG',
     'TZ',
     'UG',
     'AG',
     'AM',
     'BS',
     'BB',
     'BZ',
     'BT',
     'BW',
     'BF',
     'CV',
     'CW',
     'DM',
     'FJ',
     'GM',
     'GE',
     'GD',
     'GW',
     'GY',
     'HT',
     'JM',
     'KI',
     'LS',
     'LR',
     'MW',
     'MV',
     'ML',
     'MH',
     'FM',
     'NA',
     'NR',
     'NE',
     'PW',
     'PG',
     'WS',
     'SM',
     'ST',
     'SN',
     'SC',
     'SL',
     'SB',
     'KN',
     'LC',
     'VC',
     'SR',
     'TL',
     'TO',
     'TT',
     'TV',
     'VU',
     'AZ',
     'BN',
     'BI',
     'KH',
     'CM',
     'TD',
     'KM',
     'GQ',
     'SZ',
     'GA',
     'GN',
     'KG',
     'LA',
     'MO',
     'MR',
     'MN',
     'NP',
     'RW',
     'TG',
     'UZ',
     'ZW',
     'BJ',
     'MG',
     'MU',
     'MZ',
     'AO',
     'CI',
     'DJ',
     'ZM',
     'CD',
     'CG',
     'IQ',
     'LY',
     'TJ',
     'VE',
     'ET',
     'XK'],
    'type': 'album',
    'album_type': 'album',
    'href': 'https://api.spotify.com/v1/albums/3HNnxK7NgLXbDoxRZxNWiR',
    'id': '3HNnxK7NgLXbDoxRZxNWiR',
    'images': [{'height': 640,
      'url': 'https://i.scdn.co/image/ab67616d0000b273e4073def0c03a91e3fceaf73',
      'width': 640},
     {'height': 300,
      'url': 'https://i.scdn.co/image/ab67616d00001e02e4073def0c03a91e3fceaf73',
      'width': 300},
     {'height': 64,
      'url': 'https://i.scdn.co/image/ab67616d00004851e4073def0c03a91e3fceaf73',
      'width': 64}],
    'name': 'Kamikaze',
    'release_date': '2018-08-31',
    'release_date_precision': 'day',
    'uri': 'spotify:album:3HNnxK7NgLXbDoxRZxNWiR',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR'},
      'href': 'https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR',
      'id': '7dGJo4pcD2V6oG8kP0tJRR',
      'name': 'Eminem',
      'type': 'artist',
      'uri': 'spotify:artist:7dGJo4pcD2V6oG8kP0tJRR'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/3HNnxK7NgLXbDoxRZxNWiR'},
    'total_tracks': 13},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR'},
     'href': 'https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR',
     'id': '7dGJo4pcD2V6oG8kP0tJRR',
     'name': 'Eminem',
     'type': 'artist',
     'uri': 'spotify:artist:7dGJo4pcD2V6oG8kP0tJRR'},
    {'external_urls': {'spotify': 'https://open.spotify.com/artist/6C1ohJrd5VydigQtaGy5Wa'},
     'href': 'https://api.spotify.com/v1/artists/6C1ohJrd5VydigQtaGy5Wa',
     'id': '6C1ohJrd5VydigQtaGy5Wa',
     'name': 'Joyner Lucas',
     'type': 'artist',
     'uri': 'spotify:artist:6C1ohJrd5VydigQtaGy5Wa'}],
   'disc_number': 1,
   'track_number': 3,
   'duration_ms': 244679,
   'external_ids': {'isrc': 'USUM71813334'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/60SdxE8apGAxMiRrpbmLY0'},
   'href': 'https://api.spotify.com/v1/tracks/60SdxE8apGAxMiRrpbmLY0',
   'id': '60SdxE8apGAxMiRrpbmLY0',
   'name': 'Lucky You (feat. Joyner Lucas)',
   'popularity': 70,
   'uri': 'spotify:track:60SdxE8apGAxMiRrpbmLY0',
   'is_local': False},
  'video_thumbnail': {'url': None}},
 {'added_at': '2018-09-20T16:07:04Z',
  'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/evebvb6vpgyn9xtip57ou6087'},
   'href': 'https://api.spotify.com/v1/users/evebvb6vpgyn9xtip57ou6087',
   'id': 'evebvb6vpgyn9xtip57ou6087',
   'type': 'user',
   'uri': 'spotify:user:evebvb6vpgyn9xtip57ou6087'},
  'is_local': False,
  'primary_color': None,
  'track': {'preview_url': None,
   'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'BY',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'RW',
    'TG',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'explicit': True,
   'type': 'track',
   'episode': False,
   'track': True,
   'album': {'available_markets': ['AR',
     'AU',
     'AT',
     'BE',
     'BO',
     'BR',
     'BG',
     'CA',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DK',
     'DO',
     'DE',
     'EC',
     'EE',
     'SV',
     'FI',
     'FR',
     'GR',
     'GT',
     'HN',
     'HK',
     'HU',
     'IS',
     'IE',
     'IT',
     'LV',
     'LT',
     'LU',
     'MY',
     'MT',
     'MX',
     'NL',
     'NZ',
     'NI',
     'NO',
     'PA',
     'PY',
     'PE',
     'PH',
     'PL',
     'PT',
     'SG',
     'SK',
     'ES',
     'SE',
     'CH',
     'TW',
     'TR',
     'UY',
     'US',
     'GB',
     'AD',
     'LI',
     'MC',
     'ID',
     'JP',
     'TH',
     'VN',
     'RO',
     'IL',
     'ZA',
     'SA',
     'AE',
     'BH',
     'QA',
     'OM',
     'KW',
     'EG',
     'MA',
     'DZ',
     'TN',
     'LB',
     'JO',
     'PS',
     'IN',
     'BY',
     'KZ',
     'MD',
     'UA',
     'AL',
     'BA',
     'HR',
     'ME',
     'MK',
     'RS',
     'SI',
     'KR',
     'BD',
     'PK',
     'LK',
     'GH',
     'KE',
     'NG',
     'TZ',
     'UG',
     'AG',
     'AM',
     'BS',
     'BB',
     'BZ',
     'BT',
     'BW',
     'CV',
     'CW',
     'DM',
     'FJ',
     'GM',
     'GE',
     'GD',
     'GW',
     'GY',
     'HT',
     'JM',
     'KI',
     'LS',
     'LR',
     'MW',
     'MV',
     'ML',
     'MH',
     'FM',
     'NA',
     'NR',
     'NE',
     'PW',
     'PG',
     'WS',
     'SM',
     'ST',
     'SN',
     'SC',
     'SL',
     'SB',
     'KN',
     'LC',
     'VC',
     'SR',
     'TL',
     'TO',
     'TT',
     'TV',
     'VU',
     'AZ',
     'BI',
     'KH',
     'CM',
     'TD',
     'KM',
     'GQ',
     'SZ',
     'GA',
     'GN',
     'KG',
     'LA',
     'MO',
     'MR',
     'MN',
     'RW',
     'TG',
     'ZW',
     'BJ',
     'MG',
     'MU',
     'MZ',
     'AO',
     'CI',
     'DJ',
     'ZM',
     'CD',
     'CG',
     'IQ',
     'LY',
     'TJ',
     'VE',
     'ET',
     'XK'],
    'type': 'album',
    'album_type': 'album',
    'href': 'https://api.spotify.com/v1/albums/1ATL5GLyefJaxhQzSPVrLX',
    'id': '1ATL5GLyefJaxhQzSPVrLX',
    'images': [{'height': 640,
      'url': 'https://i.scdn.co/image/ab67616d0000b273f907de96b9a4fbc04accc0d5',
      'width': 640},
     {'height': 300,
      'url': 'https://i.scdn.co/image/ab67616d00001e02f907de96b9a4fbc04accc0d5',
      'width': 300},
     {'height': 64,
      'url': 'https://i.scdn.co/image/ab67616d00004851f907de96b9a4fbc04accc0d5',
      'width': 64}],
    'name': 'Scorpion',
    'release_date': '2018-06-29',
    'release_date_precision': 'day',
    'uri': 'spotify:album:1ATL5GLyefJaxhQzSPVrLX',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3TVXtAsR1Inumwj472S9r4'},
      'href': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4',
      'id': '3TVXtAsR1Inumwj472S9r4',
      'name': 'Drake',
      'type': 'artist',
      'uri': 'spotify:artist:3TVXtAsR1Inumwj472S9r4'}],
    'external_urls': {'spotify': 'https://open.spotify.com/album/1ATL5GLyefJaxhQzSPVrLX'},
    'total_tracks': 25},
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3TVXtAsR1Inumwj472S9r4'},
     'href': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4',
     'id': '3TVXtAsR1Inumwj472S9r4',
     'name': 'Drake',
     'type': 'artist',
     'uri': 'spotify:artist:3TVXtAsR1Inumwj472S9r4'}],
   'disc_number': 2,
   'track_number': 9,
   'duration_ms': 217925,
   'external_ids': {'isrc': 'USCM51800206'},
   'external_urls': {'spotify': 'https://open.spotify.com/track/2G7V7zsVDxg1yRsu7Ew9RJ'},
   'href': 'https://api.spotify.com/v1/tracks/2G7V7zsVDxg1yRsu7Ew9RJ',
   'id': '2G7V7zsVDxg1yRsu7Ew9RJ',
   'name': 'In My Feelings',
   'popularity': 75,
   'uri': 'spotify:track:2G7V7zsVDxg1yRsu7Ew9RJ',
   'is_local': False},
  'video_thumbnail': {'url': None}},
 {'added_at': '2018-09-20T16:07:04Z',
  'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/evebvb6vpgyn9xtip57ou6087'},
   'href': 'https://api.spotify.com/v1/users/evebvb6vpgyn9xtip57ou6087',
   'id': 'evebvb6vpgyn9xtip57ou6087',
   'type': 'user',
   'uri': 'spotify:user:evebvb6vpgyn9xtip57ou6087'},

In [150]:
len(data['items'])

100

In [152]:
data['items'][0]

{'added_at': '2018-09-20T16:07:04Z',
 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/evebvb6vpgyn9xtip57ou6087'},
  'href': 'https://api.spotify.com/v1/users/evebvb6vpgyn9xtip57ou6087',
  'id': 'evebvb6vpgyn9xtip57ou6087',
  'type': 'user',
  'uri': 'spotify:user:evebvb6vpgyn9xtip57ou6087'},
 'is_local': False,
 'primary_color': None,
 'track': {'preview_url': None,
  'available_markets': ['AR',
   'AU',
   'AT',
   'BE',
   'BO',
   'BR',
   'BG',
   'CA',
   'CL',
   'CO',
   'CR',
   'CY',
   'CZ',
   'DK',
   'DO',
   'DE',
   'EC',
   'EE',
   'SV',
   'FI',
   'FR',
   'GR',
   'GT',
   'HN',
   'HK',
   'HU',
   'IS',
   'IE',
   'IT',
   'LV',
   'LT',
   'LU',
   'MY',
   'MT',
   'MX',
   'NL',
   'NZ',
   'NI',
   'NO',
   'PA',
   'PY',
   'PE',
   'PH',
   'PL',
   'PT',
   'SG',
   'SK',
   'ES',
   'SE',
   'CH',
   'TW',
   'TR',
   'UY',
   'US',
   'GB',
   'AD',
   'LI',
   'MC',
   'ID',
   'JP',
   'TH',
   'VN',
   'RO',
   'IL',
   'ZA',
   'SA',
   'AE',
   'BH',
   'QA',
   'OM',
   'KW',
   'EG',
   'MA',
   'DZ',
   'TN',
   'LB',
   'JO',
   'PS',
   'IN',
   'KZ',
   'MD',
   'UA',
   'AL',
   'BA',
   'HR',
   'ME',
   'MK',
   'RS',
   'SI',
   'KR',
   'BD',
   'PK',
   'LK',
   'GH',
   'KE',
   'NG',
   'TZ',
   'UG',
   'AG',
   'AM',
   'BS',
   'BB',
   'BZ',
   'BT',
   'BW',
   'CV',
   'CW',
   'DM',
   'FJ',
   'GM',
   'GE',
   'GD',
   'GW',
   'GY',
   'HT',
   'JM',
   'KI',
   'LS',
   'LR',
   'MW',
   'MV',
   'ML',
   'MH',
   'FM',
   'NA',
   'NR',
   'NE',
   'PW',
   'PG',
   'WS',
   'SM',
   'ST',
   'SN',
   'SC',
   'SL',
   'SB',
   'KN',
   'LC',
   'VC',
   'SR',
   'TL',
   'TO',
   'TT',
   'TV',
   'VU',
   'AZ',
   'BI',
   'KH',
   'CM',
   'TD',
   'KM',
   'GQ',
   'SZ',
   'GA',
   'GN',
   'KG',
   'LA',
   'MO',
   'MR',
   'MN',
   'RW',
   'TG',
   'ZW',
   'BJ',
   'MG',
   'MU',
   'MZ',
   'AO',
   'CI',
   'DJ',
   'ZM',
   'CD',
   'CG',
   'IQ',
   'LY',
   'TJ',
   'VE',
   'ET',
   'XK'],
  'explicit': True,
  'type': 'track',
  'episode': False,
  'track': True,
  'album': {'available_markets': ['AR',
    'AU',
    'AT',
    'BE',
    'BO',
    'BR',
    'BG',
    'CA',
    'CL',
    'CO',
    'CR',
    'CY',
    'CZ',
    'DK',
    'DO',
    'DE',
    'EC',
    'EE',
    'SV',
    'FI',
    'FR',
    'GR',
    'GT',
    'HN',
    'HK',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MY',
    'MT',
    'MX',
    'NL',
    'NZ',
    'NI',
    'NO',
    'PA',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'SG',
    'SK',
    'ES',
    'SE',
    'CH',
    'TW',
    'TR',
    'UY',
    'US',
    'GB',
    'AD',
    'LI',
    'MC',
    'ID',
    'JP',
    'TH',
    'VN',
    'RO',
    'IL',
    'ZA',
    'SA',
    'AE',
    'BH',
    'QA',
    'OM',
    'KW',
    'EG',
    'MA',
    'DZ',
    'TN',
    'LB',
    'JO',
    'PS',
    'IN',
    'KZ',
    'MD',
    'UA',
    'AL',
    'BA',
    'HR',
    'ME',
    'MK',
    'RS',
    'SI',
    'KR',
    'BD',
    'PK',
    'LK',
    'GH',
    'KE',
    'NG',
    'TZ',
    'UG',
    'AG',
    'AM',
    'BS',
    'BB',
    'BZ',
    'BT',
    'BW',
    'CV',
    'CW',
    'DM',
    'FJ',
    'GM',
    'GE',
    'GD',
    'GW',
    'GY',
    'HT',
    'JM',
    'KI',
    'LS',
    'LR',
    'MW',
    'MV',
    'ML',
    'MH',
    'FM',
    'NA',
    'NR',
    'NE',
    'PW',
    'PG',
    'WS',
    'SM',
    'ST',
    'SN',
    'SC',
    'SL',
    'SB',
    'KN',
    'LC',
    'VC',
    'SR',
    'TL',
    'TO',
    'TT',
    'TV',
    'VU',
    'AZ',
    'BI',
    'KH',
    'CM',
    'TD',
    'KM',
    'GQ',
    'SZ',
    'GA',
    'GN',
    'KG',
    'LA',
    'MO',
    'MR',
    'MN',
    'RW',
    'TG',
    'ZW',
    'BJ',
    'MG',
    'MU',
    'MZ',
    'AO',
    'CI',
    'DJ',
    'ZM',
    'CD',
    'CG',
    'IQ',
    'LY',
    'TJ',
    'VE',
    'ET',
    'XK'],
   'type': 'album',
   'album_type': 'single',
   'href': 'https://api.spotify.com/v1/albums/185Tm1g5U7eMOrm3m9SQUh',
   'id': '185Tm1g5U7eMOrm3m9SQUh',
   'images': [{'height': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b273b6d544387b04e1d1a5f7926c',
     'width': 640},
    {'height': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e02b6d544387b04e1d1a5f7926c',
     'width': 300},
    {'height': 64,
     'url': 'https://i.scdn.co/image/ab67616d00004851b6d544387b04e1d1a5f7926c',
     'width': 64}],
   'name': 'I Love It',
   'release_date': '2018-09-07',
   'release_date_precision': 'day',
   'uri': 'spotify:album:185Tm1g5U7eMOrm3m9SQUh',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x'},
     'href': 'https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x',
     'id': '5K4W6rqBFWDnAN6FQUkS6x',
     'name': 'Kanye West',
     'type': 'artist',
     'uri': 'spotify:artist:5K4W6rqBFWDnAN6FQUkS6x'},
    {'external_urls': {'spotify': 'https://open.spotify.com/artist/3wyVrVrFCkukjdVIdirGVY'},
     'href': 'https://api.spotify.com/v1/artists/3wyVrVrFCkukjdVIdirGVY',
     'id': '3wyVrVrFCkukjdVIdirGVY',
     'name': 'Lil Pump',
     'type': 'artist',
     'uri': 'spotify:artist:3wyVrVrFCkukjdVIdirGVY'}],
   'external_urls': {'spotify': 'https://open.spotify.com/album/185Tm1g5U7eMOrm3m9SQUh'},
   'total_tracks': 1},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x'},
    'href': 'https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x',
    'id': '5K4W6rqBFWDnAN6FQUkS6x',
    'name': 'Kanye West',
    'type': 'artist',
    'uri': 'spotify:artist:5K4W6rqBFWDnAN6FQUkS6x'},
   {'external_urls': {'spotify': 'https://open.spotify.com/artist/3wyVrVrFCkukjdVIdirGVY'},
    'href': 'https://api.spotify.com/v1/artists/3wyVrVrFCkukjdVIdirGVY',
    'id': '3wyVrVrFCkukjdVIdirGVY',
    'name': 'Lil Pump',
    'type': 'artist',
    'uri': 'spotify:artist:3wyVrVrFCkukjdVIdirGVY'}],
  'disc_number': 1,
  'track_number': 1,
  'duration_ms': 127946,
  'external_ids': {'isrc': 'USUM71814031'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/4S8d14HvHb70ImctNgVzQQ'},
  'href': 'https://api.spotify.com/v1/tracks/4S8d14HvHb70ImctNgVzQQ',
  'id': '4S8d14HvHb70ImctNgVzQQ',
  'name': 'I Love It (& Lil Pump)',
  'popularity': 69,
  'uri': 'spotify:track:4S8d14HvHb70ImctNgVzQQ',
  'is_local': False},
 'video_thumbnail': {'url': None}}

In [164]:
data['items'][0]['track']

{'preview_url': None,
 'available_markets': ['AR',
  'AU',
  'AT',
  'BE',
  'BO',
  'BR',
  'BG',
  'CA',
  'CL',
  'CO',
  'CR',
  'CY',
  'CZ',
  'DK',
  'DO',
  'DE',
  'EC',
  'EE',
  'SV',
  'FI',
  'FR',
  'GR',
  'GT',
  'HN',
  'HK',
  'HU',
  'IS',
  'IE',
  'IT',
  'LV',
  'LT',
  'LU',
  'MY',
  'MT',
  'MX',
  'NL',
  'NZ',
  'NI',
  'NO',
  'PA',
  'PY',
  'PE',
  'PH',
  'PL',
  'PT',
  'SG',
  'SK',
  'ES',
  'SE',
  'CH',
  'TW',
  'TR',
  'UY',
  'US',
  'GB',
  'AD',
  'LI',
  'MC',
  'ID',
  'JP',
  'TH',
  'VN',
  'RO',
  'IL',
  'ZA',
  'SA',
  'AE',
  'BH',
  'QA',
  'OM',
  'KW',
  'EG',
  'MA',
  'DZ',
  'TN',
  'LB',
  'JO',
  'PS',
  'IN',
  'KZ',
  'MD',
  'UA',
  'AL',
  'BA',
  'HR',
  'ME',
  'MK',
  'RS',
  'SI',
  'KR',
  'BD',
  'PK',
  'LK',
  'GH',
  'KE',
  'NG',
  'TZ',
  'UG',
  'AG',
  'AM',
  'BS',
  'BB',
  'BZ',
  'BT',
  'BW',
  'CV',
  'CW',
  'DM',
  'FJ',
  'GM',
  'GE',
  'GD',
  'GW',
  'GY',
  'HT',
  'JM',
  'KI',
  'LS',
  'LR',
  'MW',
  'MV',
  'ML',
  'MH',
  'FM',
  'NA',
  'NR',
  'NE',
  'PW',
  'PG',
  'WS',
  'SM',
  'ST',
  'SN',
  'SC',
  'SL',
  'SB',
  'KN',
  'LC',
  'VC',
  'SR',
  'TL',
  'TO',
  'TT',
  'TV',
  'VU',
  'AZ',
  'BI',
  'KH',
  'CM',
  'TD',
  'KM',
  'GQ',
  'SZ',
  'GA',
  'GN',
  'KG',
  'LA',
  'MO',
  'MR',
  'MN',
  'RW',
  'TG',
  'ZW',
  'BJ',
  'MG',
  'MU',
  'MZ',
  'AO',
  'CI',
  'DJ',
  'ZM',
  'CD',
  'CG',
  'IQ',
  'LY',
  'TJ',
  'VE',
  'ET',
  'XK'],
 'explicit': True,
 'type': 'track',
 'episode': False,
 'track': True,
 'album': {'available_markets': ['AR',
   'AU',
   'AT',
   'BE',
   'BO',
   'BR',
   'BG',
   'CA',
   'CL',
   'CO',
   'CR',
   'CY',
   'CZ',
   'DK',
   'DO',
   'DE',
   'EC',
   'EE',
   'SV',
   'FI',
   'FR',
   'GR',
   'GT',
   'HN',
   'HK',
   'HU',
   'IS',
   'IE',
   'IT',
   'LV',
   'LT',
   'LU',
   'MY',
   'MT',
   'MX',
   'NL',
   'NZ',
   'NI',
   'NO',
   'PA',
   'PY',
   'PE',
   'PH',
   'PL',
   'PT',
   'SG',
   'SK',
   'ES',
   'SE',
   'CH',
   'TW',
   'TR',
   'UY',
   'US',
   'GB',
   'AD',
   'LI',
   'MC',
   'ID',
   'JP',
   'TH',
   'VN',
   'RO',
   'IL',
   'ZA',
   'SA',
   'AE',
   'BH',
   'QA',
   'OM',
   'KW',
   'EG',
   'MA',
   'DZ',
   'TN',
   'LB',
   'JO',
   'PS',
   'IN',
   'KZ',
   'MD',
   'UA',
   'AL',
   'BA',
   'HR',
   'ME',
   'MK',
   'RS',
   'SI',
   'KR',
   'BD',
   'PK',
   'LK',
   'GH',
   'KE',
   'NG',
   'TZ',
   'UG',
   'AG',
   'AM',
   'BS',
   'BB',
   'BZ',
   'BT',
   'BW',
   'CV',
   'CW',
   'DM',
   'FJ',
   'GM',
   'GE',
   'GD',
   'GW',
   'GY',
   'HT',
   'JM',
   'KI',
   'LS',
   'LR',
   'MW',
   'MV',
   'ML',
   'MH',
   'FM',
   'NA',
   'NR',
   'NE',
   'PW',
   'PG',
   'WS',
   'SM',
   'ST',
   'SN',
   'SC',
   'SL',
   'SB',
   'KN',
   'LC',
   'VC',
   'SR',
   'TL',
   'TO',
   'TT',
   'TV',
   'VU',
   'AZ',
   'BI',
   'KH',
   'CM',
   'TD',
   'KM',
   'GQ',
   'SZ',
   'GA',
   'GN',
   'KG',
   'LA',
   'MO',
   'MR',
   'MN',
   'RW',
   'TG',
   'ZW',
   'BJ',
   'MG',
   'MU',
   'MZ',
   'AO',
   'CI',
   'DJ',
   'ZM',
   'CD',
   'CG',
   'IQ',
   'LY',
   'TJ',
   'VE',
   'ET',
   'XK'],
  'type': 'album',
  'album_type': 'single',
  'href': 'https://api.spotify.com/v1/albums/185Tm1g5U7eMOrm3m9SQUh',
  'id': '185Tm1g5U7eMOrm3m9SQUh',
  'images': [{'height': 640,
    'url': 'https://i.scdn.co/image/ab67616d0000b273b6d544387b04e1d1a5f7926c',
    'width': 640},
   {'height': 300,
    'url': 'https://i.scdn.co/image/ab67616d00001e02b6d544387b04e1d1a5f7926c',
    'width': 300},
   {'height': 64,
    'url': 'https://i.scdn.co/image/ab67616d00004851b6d544387b04e1d1a5f7926c',
    'width': 64}],
  'name': 'I Love It',
  'release_date': '2018-09-07',
  'release_date_precision': 'day',
  'uri': 'spotify:album:185Tm1g5U7eMOrm3m9SQUh',
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x'},
    'href': 'https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x',
    'id': '5K4W6rqBFWDnAN6FQUkS6x',
    'name': 'Kanye West',
    'type': 'artist',
    'uri': 'spotify:artist:5K4W6rqBFWDnAN6FQUkS6x'},
   {'external_urls': {'spotify': 'https://open.spotify.com/artist/3wyVrVrFCkukjdVIdirGVY'},
    'href': 'https://api.spotify.com/v1/artists/3wyVrVrFCkukjdVIdirGVY',
    'id': '3wyVrVrFCkukjdVIdirGVY',
    'name': 'Lil Pump',
    'type': 'artist',
    'uri': 'spotify:artist:3wyVrVrFCkukjdVIdirGVY'}],
  'external_urls': {'spotify': 'https://open.spotify.com/album/185Tm1g5U7eMOrm3m9SQUh'},
  'total_tracks': 1},
 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x'},
   'href': 'https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x',
   'id': '5K4W6rqBFWDnAN6FQUkS6x',
   'name': 'Kanye West',
   'type': 'artist',
   'uri': 'spotify:artist:5K4W6rqBFWDnAN6FQUkS6x'},
  {'external_urls': {'spotify': 'https://open.spotify.com/artist/3wyVrVrFCkukjdVIdirGVY'},
   'href': 'https://api.spotify.com/v1/artists/3wyVrVrFCkukjdVIdirGVY',
   'id': '3wyVrVrFCkukjdVIdirGVY',
   'name': 'Lil Pump',
   'type': 'artist',
   'uri': 'spotify:artist:3wyVrVrFCkukjdVIdirGVY'}],
 'disc_number': 1,
 'track_number': 1,
 'duration_ms': 127946,
 'external_ids': {'isrc': 'USUM71814031'},
 'external_urls': {'spotify': 'https://open.spotify.com/track/4S8d14HvHb70ImctNgVzQQ'},
 'href': 'https://api.spotify.com/v1/tracks/4S8d14HvHb70ImctNgVzQQ',
 'id': '4S8d14HvHb70ImctNgVzQQ',
 'name': 'I Love It (& Lil Pump)',
 'popularity': 69,
 'uri': 'spotify:track:4S8d14HvHb70ImctNgVzQQ',
 'is_local': False}

In [168]:
data['items'][0]['track']['album']

{'available_markets': ['AR',
  'AU',
  'AT',
  'BE',
  'BO',
  'BR',
  'BG',
  'CA',
  'CL',
  'CO',
  'CR',
  'CY',
  'CZ',
  'DK',
  'DO',
  'DE',
  'EC',
  'EE',
  'SV',
  'FI',
  'FR',
  'GR',
  'GT',
  'HN',
  'HK',
  'HU',
  'IS',
  'IE',
  'IT',
  'LV',
  'LT',
  'LU',
  'MY',
  'MT',
  'MX',
  'NL',
  'NZ',
  'NI',
  'NO',
  'PA',
  'PY',
  'PE',
  'PH',
  'PL',
  'PT',
  'SG',
  'SK',
  'ES',
  'SE',
  'CH',
  'TW',
  'TR',
  'UY',
  'US',
  'GB',
  'AD',
  'LI',
  'MC',
  'ID',
  'JP',
  'TH',
  'VN',
  'RO',
  'IL',
  'ZA',
  'SA',
  'AE',
  'BH',
  'QA',
  'OM',
  'KW',
  'EG',
  'MA',
  'DZ',
  'TN',
  'LB',
  'JO',
  'PS',
  'IN',
  'KZ',
  'MD',
  'UA',
  'AL',
  'BA',
  'HR',
  'ME',
  'MK',
  'RS',
  'SI',
  'KR',
  'BD',
  'PK',
  'LK',
  'GH',
  'KE',
  'NG',
  'TZ',
  'UG',
  'AG',
  'AM',
  'BS',
  'BB',
  'BZ',
  'BT',
  'BW',
  'CV',
  'CW',
  'DM',
  'FJ',
  'GM',
  'GE',
  'GD',
  'GW',
  'GY',
  'HT',
  'JM',
  'KI',
  'LS',
  'LR',
  'MW',
  'MV',
  'ML',
  'MH',
  'FM',
  'NA',
  'NR',
  'NE',
  'PW',
  'PG',
  'WS',
  'SM',
  'ST',
  'SN',
  'SC',
  'SL',
  'SB',
  'KN',
  'LC',
  'VC',
  'SR',
  'TL',
  'TO',
  'TT',
  'TV',
  'VU',
  'AZ',
  'BI',
  'KH',
  'CM',
  'TD',
  'KM',
  'GQ',
  'SZ',
  'GA',
  'GN',
  'KG',
  'LA',
  'MO',
  'MR',
  'MN',
  'RW',
  'TG',
  'ZW',
  'BJ',
  'MG',
  'MU',
  'MZ',
  'AO',
  'CI',
  'DJ',
  'ZM',
  'CD',
  'CG',
  'IQ',
  'LY',
  'TJ',
  'VE',
  'ET',
  'XK'],
 'type': 'album',
 'album_type': 'single',
 'href': 'https://api.spotify.com/v1/albums/185Tm1g5U7eMOrm3m9SQUh',
 'id': '185Tm1g5U7eMOrm3m9SQUh',
 'images': [{'height': 640,
   'url': 'https://i.scdn.co/image/ab67616d0000b273b6d544387b04e1d1a5f7926c',
   'width': 640},
  {'height': 300,
   'url': 'https://i.scdn.co/image/ab67616d00001e02b6d544387b04e1d1a5f7926c',
   'width': 300},
  {'height': 64,
   'url': 'https://i.scdn.co/image/ab67616d00004851b6d544387b04e1d1a5f7926c',
   'width': 64}],
 'name': 'I Love It',
 'release_date': '2018-09-07',
 'release_date_precision': 'day',
 'uri': 'spotify:album:185Tm1g5U7eMOrm3m9SQUh',
 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x'},
   'href': 'https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x',
   'id': '5K4W6rqBFWDnAN6FQUkS6x',
   'name': 'Kanye West',
   'type': 'artist',
   'uri': 'spotify:artist:5K4W6rqBFWDnAN6FQUkS6x'},
  {'external_urls': {'spotify': 'https://open.spotify.com/artist/3wyVrVrFCkukjdVIdirGVY'},
   'href': 'https://api.spotify.com/v1/artists/3wyVrVrFCkukjdVIdirGVY',
   'id': '3wyVrVrFCkukjdVIdirGVY',
   'name': 'Lil Pump',
   'type': 'artist',
   'uri': 'spotify:artist:3wyVrVrFCkukjdVIdirGVY'}],
 'external_urls': {'spotify': 'https://open.spotify.com/album/185Tm1g5U7eMOrm3m9SQUh'},
 'total_tracks': 1}

In [170]:
data['items'][0]['track']['album']['id']

'185Tm1g5U7eMOrm3m9SQUh'

In [172]:
data['items'][0]['track']['album']['name']

'I Love It'

In [174]:
data['items'][0]['track']['album']['total_tracks']

1

In [188]:
data['items'][0]['track']['album']['release_date']

'2018-09-07'

In [176]:
data['items'][0]['track']['album']['external_urls']['spotify']

'https://open.spotify.com/album/185Tm1g5U7eMOrm3m9SQUh'

In [178]:
album_list = []
for row in data['items']:
    album_id = row['track']['album']['id']
    album_name = row['track']['album']['name']
    album_release_date = row['track']['album']['release_date']
    album_total_tracks = row['track']['album']['total_tracks']
    album_url = row['track']['album']['external_urls']['spotify']
    album_element = {'album_id':album_id,'name':album_name,'release_date':album_release_date,
                        'total_tracks':album_total_tracks,'url':album_url}
    album_list.append(album_element)

In [192]:
print(album_list)

[{'album_id': '185Tm1g5U7eMOrm3m9SQUh', 'name': 'I Love It', 'release_date': '2018-09-07', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/185Tm1g5U7eMOrm3m9SQUh'}, {'album_id': '3HNnxK7NgLXbDoxRZxNWiR', 'name': 'Kamikaze', 'release_date': '2018-08-31', 'total_tracks': 13, 'url': 'https://open.spotify.com/album/3HNnxK7NgLXbDoxRZxNWiR'}, {'album_id': '1ATL5GLyefJaxhQzSPVrLX', 'name': 'Scorpion', 'release_date': '2018-06-29', 'total_tracks': 25, 'url': 'https://open.spotify.com/album/1ATL5GLyefJaxhQzSPVrLX'}, {'album_id': '7pkLXlFdpQDfmHujT2AbBK', 'name': 'Eastside (with Halsey & Khalid)', 'release_date': '2018-07-12', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/7pkLXlFdpQDfmHujT2AbBK'}, {'album_id': '78EicdHZr5XBWD7llEZ1Jh', 'name': 'Happier', 'release_date': '2018-08-17', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/78EicdHZr5XBWD7llEZ1Jh'}, {'album_id': '2tpWgbBdzjkaJVJzR4T8y1', 'name': 'Promises (with Sam Smith)', 'release_date': '2018-08-17', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/2tpWgbBdzjkaJVJzR4T8y1'}, {'album_id': '1c79SozES9Eb3Lzf9KVaIa', 'name': 'In My Mind', 'release_date': '2018-06-08', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/1c79SozES9Eb3Lzf9KVaIa'}, {'album_id': '41GuZcammIkupMPKH2OJ6I', 'name': 'ASTROWORLD', 'release_date': '2018-08-03', 'total_tracks': 17, 'url': 'https://open.spotify.com/album/41GuZcammIkupMPKH2OJ6I'}, {'album_id': '1Li4rADxSxjT2g4xqUcMYh', 'name': 'Red Pill Blues (Deluxe)', 'release_date': '2018-06-15', 'total_tracks': 22, 'url': 'https://open.spotify.com/album/1Li4rADxSxjT2g4xqUcMYh'}, {'album_id': '2viWIVEItaDlFH2RXWKwS7', 'name': 'Goodbye & Good Riddance', 'release_date': '2018-05-23', 'total_tracks': 16, 'url': 'https://open.spotify.com/album/2viWIVEItaDlFH2RXWKwS7'}, {'album_id': '0gjZidNFs7O2qqE2Z5elJ3', 'name': 'FEFE (feat. Nicki Minaj & Murda Beatz)', 'release_date': '2018-07-22', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/0gjZidNFs7O2qqE2Z5elJ3'}, {'album_id': '3J0AWftMu0tsXw22obufYn', 'name': 'Falling Down (Bonus Track)', 'release_date': '2018-09-19', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/3J0AWftMu0tsXw22obufYn'}, {'album_id': '0YZLXTaHLcgl5UdtKDiUXD', 'name': 'Be Alright', 'release_date': '2018-06-29', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/0YZLXTaHLcgl5UdtKDiUXD'}, {'album_id': '64eE6FnNj7UJ9LEkN4EbvS', 'name': 'New Patek', 'release_date': '2018-09-18', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/64eE6FnNj7UJ9LEkN4EbvS'}, {'album_id': '6Nd4PYvQ7aYid1Gn6sWgeG', 'name': 'Better', 'release_date': '2018-09-14', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/6Nd4PYvQ7aYid1Gn6sWgeG'}, {'album_id': '2Ti79nwTsont5ZHfdxIzAm', 'name': '?', 'release_date': '2018-03-16', 'total_tracks': 18, 'url': 'https://open.spotify.com/album/2Ti79nwTsont5ZHfdxIzAm'}, {'album_id': '429B3se6xtZuvblNnS2iy7', 'name': 'Electricity', 'release_date': '2018-09-06', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/429B3se6xtZuvblNnS2iy7'}, {'album_id': '0yd01cU78rnlFXq6vRxPSR', 'name': 'Taste (feat. Offset)', 'release_date': '2018-05-16', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/0yd01cU78rnlFXq6vRxPSR'}, {'album_id': '02drHFQa59AoJWU6DXSSjd', 'name': 'No Brainer', 'release_date': '2018-07-27', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/02drHFQa59AoJWU6DXSSjd'}, {'album_id': '4KdtEKjY3Gi0mKiSdy96ML', 'name': 'Invasion of Privacy', 'release_date': '2018-04-06', 'total_tracks': 13, 'url': 'https://open.spotify.com/album/4KdtEKjY3Gi0mKiSdy96ML'}, {'album_id': '3rar7GKCodqR9GIIiNe75H', 'name': 'Natural', 'release_date': '2018-07-17', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/3rar7GKCodqR9GIIiNe75H'}, {'album_id': '0SukGZiXMtmsZoxstkBtNR', 'name': 'Aura', 'release_date': '2018-08-24', 'total_tracks': 20, 'url': 'https://open.spotify.com/album/0SukGZiXMtmsZoxstkBtNR'}, {'album_id': '3OLSEsIMEgtcn1U9s03qRR', 'name': 'BEBE', 'release_date': '2018-08-31', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/3OLSEsIMEgtcn1U9s03qRR'}, {'album_id': '6trNtQUgC8cgbWcqoMYkOR', 'name': 'beerbongs & bentleys', 'release_date': '2018-04-27', 'total_tracks': 18, 'url': 'https://open.spotify.com/album/6trNtQUgC8cgbWcqoMYkOR'}, {'album_id': '3tx8gQqWbGwqIGZHqDNrGe', 'name': 'Sweetener', 'release_date': '2018-08-17', 'total_tracks': 15, 'url': 'https://open.spotify.com/album/3tx8gQqWbGwqIGZHqDNrGe'}, {'album_id': '7fesgWyA3ehM0OFK14B9xR', 'name': 'Body (feat. brando)', 'release_date': '2017-10-27', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/7fesgWyA3ehM0OFK14B9xR'}, {'album_id': '7mkyc2BUahNfo0orKzqNGB', 'name': 'Wake Up in the Sky', 'release_date': '2018-09-14', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/7mkyc2BUahNfo0orKzqNGB'}, {'album_id': '3tx8gQqWbGwqIGZHqDNrGe', 'name': 'Sweetener', 'release_date': '2018-08-17', 'total_tracks': 15, 'url': 'https://open.spotify.com/album/3tx8gQqWbGwqIGZHqDNrGe'}, {'album_id': '3KjCdhPbjbLptyJzviKu4P', 'name': 'Rise', 'release_date': '2018-05-25', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/3KjCdhPbjbLptyJzviKu4P'}, {'album_id': '2D0Hi3Jj6RFnpWDcSa0Otu', 'name': 'Youngblood (Deluxe)', 'release_date': '2018-06-15', 'total_tracks': 16, 'url': 'https://open.spotify.com/album/2D0Hi3Jj6RFnpWDcSa0Otu'}, {'album_id': '1q7a5wZeti0neU2jDn8Dz3', 'name': 'Solo (feat. Demi Lovato)', 'release_date': '2018-05-17', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/1q7a5wZeti0neU2jDn8Dz3'}, {'album_id': '2Ti79nwTsont5ZHfdxIzAm', 'name': '?', 'release_date': '2018-03-16', 'total_tracks': 18, 'url': 'https://open.spotify.com/album/2Ti79nwTsont5ZHfdxIzAm'}, {'album_id': '1ATL5GLyefJaxhQzSPVrLX', 'name': 'Scorpion', 'release_date': '2018-06-29', 'total_tracks': 25, 'url': 'https://open.spotify.com/album/1ATL5GLyefJaxhQzSPVrLX'}, {'album_id': '6LK12zrllpjwB43YA4QX8d', 'name': 'Thunderclouds', 'release_date': '2018-08-09', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/6LK12zrllpjwB43YA4QX8d'}, {'album_id': '42wLKnuGyBLGWwH89lnimL', 'name': 'Te Boté (Remix)', 'release_date': '2018-04-13', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/42wLKnuGyBLGWwH89lnimL'}, {'album_id': '0vRcQquqBlFvnezWldWfmt', 'name': 'Jackie Chan', 'release_date': '2018-05-18', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/0vRcQquqBlFvnezWldWfmt'}, {'album_id': '3HNnxK7NgLXbDoxRZxNWiR', 'name': 'Kamikaze', 'release_date': '2018-08-31', 'total_tracks': 13, 'url': 'https://open.spotify.com/album/3HNnxK7NgLXbDoxRZxNWiR'}, {'album_id': '6hCR3zQtRH0IgookOYt771', 'name': 'Beautiful (feat. Camila Cabello)', 'release_date': '2018-08-02', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/6hCR3zQtRH0IgookOYt771'}, {'album_id': '2NaulYO6lGXTyIzWTJvRJj', 'name': "Staying at Tamara's", 'release_date': '2018-03-23', 'total_tracks': 11, 'url': 'https://open.spotify.com/album/2NaulYO6lGXTyIzWTJvRJj'}, {'album_id': '7GEzhoTiqcPYkOprWQu581', 'name': 'One Kiss (with Dua Lipa)', 'release_date': '2018-04-06', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/7GEzhoTiqcPYkOprWQu581'}, {'album_id': '5rbJtzuXtpIP0Ykk7ewIit', 'name': '7', 'release_date': '2018-09-14', 'total_tracks': 27, 'url': 'https://open.spotify.com/album/5rbJtzuXtpIP0Ykk7ewIit'}, {'album_id': '5VdyJkLe3yvOs0l4xXbWp0', 'name': '17', 'release_date': '2017-08-25', 'total_tracks': 11, 'url': 'https://open.spotify.com/album/5VdyJkLe3yvOs0l4xXbWp0'}, {'album_id': '1ATL5GLyefJaxhQzSPVrLX', 'name': 'Scorpion', 'release_date': '2018-06-29', 'total_tracks': 25, 'url': 'https://open.spotify.com/album/1ATL5GLyefJaxhQzSPVrLX'}, {'album_id': '5kprdYds6oZb4iSldfflOT', 'name': 'Vibras', 'release_date': '2018-05-25', 'total_tracks': 14, 'url': 'https://open.spotify.com/album/5kprdYds6oZb4iSldfflOT'}, {'album_id': '5dL5RSd455FewNptPgtBTS', 'name': 'Goodbye (feat. Nicki Minaj & Willy William)', 'release_date': '2018-08-24', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/5dL5RSd455FewNptPgtBTS'}, {'album_id': '3HNnxK7NgLXbDoxRZxNWiR', 'name': 'Kamikaze', 'release_date': '2018-08-31', 'total_tracks': 13, 'url': 'https://open.spotify.com/album/3HNnxK7NgLXbDoxRZxNWiR'}, {'album_id': '3tx8gQqWbGwqIGZHqDNrGe', 'name': 'Sweetener', 'release_date': '2018-08-17', 'total_tracks': 15, 'url': 'https://open.spotify.com/album/3tx8gQqWbGwqIGZHqDNrGe'}, {'album_id': '0JcW7yCW3Qj8uMfzO2lUDb', 'name': 'Happy Now', 'release_date': '2018-07-18', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/0JcW7yCW3Qj8uMfzO2lUDb'}, {'album_id': '6trNtQUgC8cgbWcqoMYkOR', 'name': 'beerbongs & bentleys', 'release_date': '2018-04-27', 'total_tracks': 18, 'url': 'https://open.spotify.com/album/6trNtQUgC8cgbWcqoMYkOR'}, {'album_id': '6hAxqfWO3xDGzjs8yad1pB', 'name': 'Sin Pijama', 'release_date': '2018-04-20', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/6hAxqfWO3xDGzjs8yad1pB'}, {'album_id': '3qowbCeEsKLpcHDgZiPMad', 'name': 'God is a woman', 'release_date': '2018-07-13', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/3qowbCeEsKLpcHDgZiPMad'}, {'album_id': '4hlAdqONoJhkjf8u9XMjQr', 'name': 'All Falls Down (feat. Juliander)', 'release_date': '2017-10-27', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/4hlAdqONoJhkjf8u9XMjQr'}, {'album_id': '2AkKk7DFnT2IV1gPcq7RCQ', 'name': 'no tears left to cry', 'release_date': '2018-04-20', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/2AkKk7DFnT2IV1gPcq7RCQ'}, {'album_id': '5pFVq0CSfbMMk6s4Kv256T', 'name': 'Mad Love', 'release_date': '2018-02-15', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/5pFVq0CSfbMMk6s4Kv256T'}, {'album_id': '47oyrKaeobswT4T8zyaxdM', 'name': 'Kids in Love', 'release_date': '2017-11-03', 'total_tracks': 9, 'url': 'https://open.spotify.com/album/47oyrKaeobswT4T8zyaxdM'}, {'album_id': '75iQSBSaztFIAun9qLLCnb', 'name': 'Girls Like You (feat. Cardi B)', 'release_date': '2018-05-30', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/75iQSBSaztFIAun9qLLCnb'}, {'album_id': '6oSxSPOg7Kuitjt2zwP7sU', 'name': '2002', 'release_date': '2018-04-19', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/6oSxSPOg7Kuitjt2zwP7sU'}, {'album_id': '2HpvpeGTBWdzBqKGLTLd3H', 'name': 'Sun In Our Eyes', 'release_date': '2018-07-12', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/2HpvpeGTBWdzBqKGLTLd3H'}, {'album_id': '6c5gDwB7Xo58thk2vap4Ch', 'name': 'Nevermind', 'release_date': '2017-06-30', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/6c5gDwB7Xo58thk2vap4Ch'}, {'album_id': '4CEAev7neETRdqBFtzA8B9', 'name': 'Love Lies', 'release_date': '2018-02-14', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/4CEAev7neETRdqBFtzA8B9'}, {'album_id': '4sqrDaJcbCIo6aeqO26maj', 'name': "Don't Leave Me Alone (feat. Anne-Marie)", 'release_date': '2018-07-26', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/4sqrDaJcbCIo6aeqO26maj'}, {'album_id': '2sjjFDjZSCYD5eBCsi0fDW', 'name': 'These Days (feat. Jess Glynne, Macklemore & Dan Caplen)', 'release_date': '2018-01-19', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/2sjjFDjZSCYD5eBCsi0fDW'}, {'album_id': '1Kix2Ho3LgJI4tmtcFdNr8', 'name': 'Fuego', 'release_date': '2018-05-19', 'total_tracks': 2, 'url': 'https://open.spotify.com/album/1Kix2Ho3LgJI4tmtcFdNr8'}, {'album_id': '0LOJHhz9ybWLVMLucHYtCe', 'name': 'REMEDY', 'release_date': '2018-08-31', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/0LOJHhz9ybWLVMLucHYtCe'}, {'album_id': '64WDoAGyTcPlSIFAiSDsB0', 'name': 'Darkside', 'release_date': '2018-07-27', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/64WDoAGyTcPlSIFAiSDsB0'}, {'album_id': '4Y6jkhla5dLnq9vfPI7gmX', 'name': 'Zooted (feat. French Montana & Farruko)', 'release_date': '2018-07-20', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/4Y6jkhla5dLnq9vfPI7gmX'}, {'album_id': '2sBB17RXTamvj7Ncps15AK', 'name': 'lovely (with Khalid)', 'release_date': '2018-04-19', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/2sBB17RXTamvj7Ncps15AK'}, {'album_id': '1XQ6XbZ6ZM1V5iEtWlYDeH', 'name': 'Ocean (feat. Khalid)', 'release_date': '2018-06-15', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/1XQ6XbZ6ZM1V5iEtWlYDeH'}, {'album_id': '5rbJtzuXtpIP0Ykk7ewIit', 'name': '7', 'release_date': '2018-09-14', 'total_tracks': 27, 'url': 'https://open.spotify.com/album/5rbJtzuXtpIP0Ykk7ewIit'}, {'album_id': '1GUfof1gHsqYjoHFym3aim', 'name': 'High On Life (feat. Bonn)', 'release_date': '2018-07-29', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/1GUfof1gHsqYjoHFym3aim'}, {'album_id': '4Mli74klkx5jMSZlqYa3Lh', 'name': 'Sick Boy', 'release_date': '2018-04-20', 'total_tracks': 4, 'url': 'https://open.spotify.com/album/4Mli74klkx5jMSZlqYa3Lh'}, {'album_id': '6KlKprVgLbkUTtynww6MQh', 'name': 'Bed (feat. Ariana Grande)', 'release_date': '2018-06-14', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/6KlKprVgLbkUTtynww6MQh'}, {'album_id': '4UsjjAKbtKzmgEz2pGbv6P', 'name': 'Right Now', 'release_date': '2018-08-24', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/4UsjjAKbtKzmgEz2pGbv6P'}, {'album_id': '31J0UqxAkl9utyC0L59Mae', 'name': 'Born To Be Yours', 'release_date': '2018-06-15', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/31J0UqxAkl9utyC0L59Mae'}, {'album_id': '1D8u1ccrRXyFMOGTEXTgTX', 'name': 'The Middle', 'release_date': '2018-01-23', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/1D8u1ccrRXyFMOGTEXTgTX'}, {'album_id': '16Qs4jnIyXe7jprnMNRddy', 'name': 'Youngblood', 'release_date': '2018-04-12', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/16Qs4jnIyXe7jprnMNRddy'}, {'album_id': '56mP4ipdgYC7y4CJnHC0Vl', 'name': 'Like I Love You', 'release_date': '2018-09-14', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/56mP4ipdgYC7y4CJnHC0Vl'}, {'album_id': '01sfgrNbnnPUEyz6GZYlt9', 'name': 'Dua Lipa (Deluxe)', 'release_date': '2017-06-02', 'total_tracks': 17, 'url': 'https://open.spotify.com/album/01sfgrNbnnPUEyz6GZYlt9'}, {'album_id': '1VZCKNtlvWJSejzfZZs9xB', 'name': "Don't Hide", 'release_date': '2018-06-29', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/1VZCKNtlvWJSejzfZZs9xB'}, {'album_id': '6nDktVazQbm8o43JqUnN5c', 'name': 'Just Wanna Love You (feat. J. Balvin)', 'release_date': '2018-09-14', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/6nDktVazQbm8o43JqUnN5c'}, {'album_id': '4Hwj8MyVYpdLEGKOFjVjQF', 'name': 'Want To', 'release_date': '2018-09-06', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/4Hwj8MyVYpdLEGKOFjVjQF'}, {'album_id': '3wX49A4zAxAhQJ0uN5FLsl', 'name': 'Audio', 'release_date': '2018-05-10', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/3wX49A4zAxAhQJ0uN5FLsl'}, {'album_id': '09uJvEy1F5GwvazqSQcYyB', 'name': 'Just Got Paid', 'release_date': '2018-09-07', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/09uJvEy1F5GwvazqSQcYyB'}, {'album_id': '1L5GP3Zuu7BvI81OJ0VkpT', 'name': 'Familiar', 'release_date': '2018-04-20', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/1L5GP3Zuu7BvI81OJ0VkpT'}, {'album_id': '1XQ6XbZ6ZM1V5iEtWlYDeH', 'name': 'Ocean (feat. Khalid)', 'release_date': '2018-06-15', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/1XQ6XbZ6ZM1V5iEtWlYDeH'}, {'album_id': '31J0UqxAkl9utyC0L59Mae', 'name': 'Born To Be Yours', 'release_date': '2018-06-15', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/31J0UqxAkl9utyC0L59Mae'}, {'album_id': '6KlKprVgLbkUTtynww6MQh', 'name': 'Bed (feat. Ariana Grande)', 'release_date': '2018-06-14', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/6KlKprVgLbkUTtynww6MQh'}, {'album_id': '1ATL5GLyefJaxhQzSPVrLX', 'name': 'Scorpion', 'release_date': '2018-06-29', 'total_tracks': 25, 'url': 'https://open.spotify.com/album/1ATL5GLyefJaxhQzSPVrLX'}, {'album_id': '3N7eWDCvfWv34xWNohdHjO', 'name': 'Back To You (From 13 Reasons Why – Season 2 Soundtrack)', 'release_date': '2018-05-10', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/3N7eWDCvfWv34xWNohdHjO'}, {'album_id': '0PypWtpDDSDP0IEg7LuoIw', 'name': 'One Day (feat. Ryan Tedder)', 'release_date': '2018-07-27', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/0PypWtpDDSDP0IEg7LuoIw'}, {'album_id': '6c5gDwB7Xo58thk2vap4Ch', 'name': 'Nevermind', 'release_date': '2017-06-30', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/6c5gDwB7Xo58thk2vap4Ch'}, {'album_id': '4DmPCrBlJGedbs6GW7EQ1m', 'name': 'Only You (with Little Mix)', 'release_date': '2018-06-22', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/4DmPCrBlJGedbs6GW7EQ1m'}, {'album_id': '6rVOUFV4qi8MgqF7na73rX', 'name': 'Connection', 'release_date': '2018-06-26', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/6rVOUFV4qi8MgqF7na73rX'}, {'album_id': '50ztaMltoS9mN9fm8R3zcW', 'name': 'Palo Santo (Deluxe)', 'release_date': '2018-07-06', 'total_tracks': 14, 'url': 'https://open.spotify.com/album/50ztaMltoS9mN9fm8R3zcW'}, {'album_id': '4TOkZvtqNpg5UHyGxCn0mS', 'name': 'Expectations', 'release_date': '2018-06-22', 'total_tracks': 14, 'url': 'https://open.spotify.com/album/4TOkZvtqNpg5UHyGxCn0mS'}, {'album_id': '3mzHuQmDLVuecodQNKUd0T', 'name': 'Growing Pains', 'release_date': '2018-06-15', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/3mzHuQmDLVuecodQNKUd0T'}, {'album_id': '43UPJEBgAwfuGufr9RsCJV', 'name': 'Dance To This (feat. Ariana Grande)', 'release_date': '2018-06-13', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/43UPJEBgAwfuGufr9RsCJV'}, {'album_id': '6XMyDP1SroC2aCiLkKw5bA', 'name': 'Too Much (feat. Timbaland)', 'release_date': '2018-08-02', 'total_tracks': 1, 'url': 'https://open.spotify.com/album/6XMyDP1SroC2aCiLkKw5bA'}, {'album_id': '15k99o4mZJ9mfpQGIOrZ45', 'name': 'Summer Pack', 'release_date': '2018-07-11', 'total_tracks': 2, 'url': 'https://open.spotify.com/album/15k99o4mZJ9mfpQGIOrZ45'}, {'album_id': '4RpgjxgSxcRwGNuWnImneN', 'name': '13 Reasons Why (Season 2)', 'release_date': '2018-05-18', 'total_tracks': 20, 'url': 'https://open.spotify.com/album/4RpgjxgSxcRwGNuWnImneN'}]

In [194]:
album_list

[{'album_id': '185Tm1g5U7eMOrm3m9SQUh',
  'name': 'I Love It',
  'release_date': '2018-09-07',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/185Tm1g5U7eMOrm3m9SQUh'},
 {'album_id': '3HNnxK7NgLXbDoxRZxNWiR',
  'name': 'Kamikaze',
  'release_date': '2018-08-31',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/3HNnxK7NgLXbDoxRZxNWiR'},
 {'album_id': '1ATL5GLyefJaxhQzSPVrLX',
  'name': 'Scorpion',
  'release_date': '2018-06-29',
  'total_tracks': 25,
  'url': 'https://open.spotify.com/album/1ATL5GLyefJaxhQzSPVrLX'},
 {'album_id': '7pkLXlFdpQDfmHujT2AbBK',
  'name': 'Eastside (with Halsey & Khalid)',
  'release_date': '2018-07-12',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/7pkLXlFdpQDfmHujT2AbBK'},
 {'album_id': '78EicdHZr5XBWD7llEZ1Jh',
  'name': 'Happier',
  'release_date': '2018-08-17',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/78EicdHZr5XBWD7llEZ1Jh'},
 {'album_id': '2tpWgbBdzjkaJVJzR4T8y1',
  'name': 'Promises (with Sam Smith)',
  'release_date': '2018-08-17',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/2tpWgbBdzjkaJVJzR4T8y1'},
 {'album_id': '1c79SozES9Eb3Lzf9KVaIa',
  'name': 'In My Mind',
  'release_date': '2018-06-08',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/1c79SozES9Eb3Lzf9KVaIa'},
 {'album_id': '41GuZcammIkupMPKH2OJ6I',
  'name': 'ASTROWORLD',
  'release_date': '2018-08-03',
  'total_tracks': 17,
  'url': 'https://open.spotify.com/album/41GuZcammIkupMPKH2OJ6I'},
 {'album_id': '1Li4rADxSxjT2g4xqUcMYh',
  'name': 'Red Pill Blues (Deluxe)',
  'release_date': '2018-06-15',
  'total_tracks': 22,
  'url': 'https://open.spotify.com/album/1Li4rADxSxjT2g4xqUcMYh'},
 {'album_id': '2viWIVEItaDlFH2RXWKwS7',
  'name': 'Goodbye & Good Riddance',
  'release_date': '2018-05-23',
  'total_tracks': 16,
  'url': 'https://open.spotify.com/album/2viWIVEItaDlFH2RXWKwS7'},
 {'album_id': '0gjZidNFs7O2qqE2Z5elJ3',
  'name': 'FEFE (feat. Nicki Minaj & Murda Beatz)',
  'release_date': '2018-07-22',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/0gjZidNFs7O2qqE2Z5elJ3'},
 {'album_id': '3J0AWftMu0tsXw22obufYn',
  'name': 'Falling Down (Bonus Track)',
  'release_date': '2018-09-19',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/3J0AWftMu0tsXw22obufYn'},
 {'album_id': '0YZLXTaHLcgl5UdtKDiUXD',
  'name': 'Be Alright',
  'release_date': '2018-06-29',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/0YZLXTaHLcgl5UdtKDiUXD'},
 {'album_id': '64eE6FnNj7UJ9LEkN4EbvS',
  'name': 'New Patek',
  'release_date': '2018-09-18',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/64eE6FnNj7UJ9LEkN4EbvS'},
 {'album_id': '6Nd4PYvQ7aYid1Gn6sWgeG',
  'name': 'Better',
  'release_date': '2018-09-14',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/6Nd4PYvQ7aYid1Gn6sWgeG'},
 {'album_id': '2Ti79nwTsont5ZHfdxIzAm',
  'name': '?',
  'release_date': '2018-03-16',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/2Ti79nwTsont5ZHfdxIzAm'},
 {'album_id': '429B3se6xtZuvblNnS2iy7',
  'name': 'Electricity',
  'release_date': '2018-09-06',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/429B3se6xtZuvblNnS2iy7'},
 {'album_id': '0yd01cU78rnlFXq6vRxPSR',
  'name': 'Taste (feat. Offset)',
  'release_date': '2018-05-16',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/0yd01cU78rnlFXq6vRxPSR'},
 {'album_id': '02drHFQa59AoJWU6DXSSjd',
  'name': 'No Brainer',
  'release_date': '2018-07-27',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/02drHFQa59AoJWU6DXSSjd'},
 {'album_id': '4KdtEKjY3Gi0mKiSdy96ML',
  'name': 'Invasion of Privacy',
  'release_date': '2018-04-06',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/4KdtEKjY3Gi0mKiSdy96ML'},
 {'album_id': '3rar7GKCodqR9GIIiNe75H',
  'name': 'Natural',
  'release_date': '2018-07-17',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/3rar7GKCodqR9GIIiNe75H'},
 {'album_id': '0SukGZiXMtmsZoxstkBtNR',
  'name': 'Aura',
  'release_date': '2018-08-24',
  'total_tracks': 20,
  'url': 'https://open.spotify.com/album/0SukGZiXMtmsZoxstkBtNR'},
 {'album_id': '3OLSEsIMEgtcn1U9s03qRR',
  'name': 'BEBE',
  'release_date': '2018-08-31',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/3OLSEsIMEgtcn1U9s03qRR'},
 {'album_id': '6trNtQUgC8cgbWcqoMYkOR',
  'name': 'beerbongs & bentleys',
  'release_date': '2018-04-27',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/6trNtQUgC8cgbWcqoMYkOR'},
 {'album_id': '3tx8gQqWbGwqIGZHqDNrGe',
  'name': 'Sweetener',
  'release_date': '2018-08-17',
  'total_tracks': 15,
  'url': 'https://open.spotify.com/album/3tx8gQqWbGwqIGZHqDNrGe'},
 {'album_id': '7fesgWyA3ehM0OFK14B9xR',
  'name': 'Body (feat. brando)',
  'release_date': '2017-10-27',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/7fesgWyA3ehM0OFK14B9xR'},
 {'album_id': '7mkyc2BUahNfo0orKzqNGB',
  'name': 'Wake Up in the Sky',
  'release_date': '2018-09-14',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/7mkyc2BUahNfo0orKzqNGB'},
 {'album_id': '3tx8gQqWbGwqIGZHqDNrGe',
  'name': 'Sweetener',
  'release_date': '2018-08-17',
  'total_tracks': 15,
  'url': 'https://open.spotify.com/album/3tx8gQqWbGwqIGZHqDNrGe'},
 {'album_id': '3KjCdhPbjbLptyJzviKu4P',
  'name': 'Rise',
  'release_date': '2018-05-25',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/3KjCdhPbjbLptyJzviKu4P'},
 {'album_id': '2D0Hi3Jj6RFnpWDcSa0Otu',
  'name': 'Youngblood (Deluxe)',
  'release_date': '2018-06-15',
  'total_tracks': 16,
  'url': 'https://open.spotify.com/album/2D0Hi3Jj6RFnpWDcSa0Otu'},
 {'album_id': '1q7a5wZeti0neU2jDn8Dz3',
  'name': 'Solo (feat. Demi Lovato)',
  'release_date': '2018-05-17',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/1q7a5wZeti0neU2jDn8Dz3'},
 {'album_id': '2Ti79nwTsont5ZHfdxIzAm',
  'name': '?',
  'release_date': '2018-03-16',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/2Ti79nwTsont5ZHfdxIzAm'},
 {'album_id': '1ATL5GLyefJaxhQzSPVrLX',
  'name': 'Scorpion',
  'release_date': '2018-06-29',
  'total_tracks': 25,
  'url': 'https://open.spotify.com/album/1ATL5GLyefJaxhQzSPVrLX'},
 {'album_id': '6LK12zrllpjwB43YA4QX8d',
  'name': 'Thunderclouds',
  'release_date': '2018-08-09',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/6LK12zrllpjwB43YA4QX8d'},
 {'album_id': '42wLKnuGyBLGWwH89lnimL',
  'name': 'Te Boté (Remix)',
  'release_date': '2018-04-13',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/42wLKnuGyBLGWwH89lnimL'},
 {'album_id': '0vRcQquqBlFvnezWldWfmt',
  'name': 'Jackie Chan',
  'release_date': '2018-05-18',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/0vRcQquqBlFvnezWldWfmt'},
 {'album_id': '3HNnxK7NgLXbDoxRZxNWiR',
  'name': 'Kamikaze',
  'release_date': '2018-08-31',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/3HNnxK7NgLXbDoxRZxNWiR'},
 {'album_id': '6hCR3zQtRH0IgookOYt771',
  'name': 'Beautiful (feat. Camila Cabello)',
  'release_date': '2018-08-02',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/6hCR3zQtRH0IgookOYt771'},
 {'album_id': '2NaulYO6lGXTyIzWTJvRJj',
  'name': "Staying at Tamara's",
  'release_date': '2018-03-23',
  'total_tracks': 11,
  'url': 'https://open.spotify.com/album/2NaulYO6lGXTyIzWTJvRJj'},
 {'album_id': '7GEzhoTiqcPYkOprWQu581',
  'name': 'One Kiss (with Dua Lipa)',
  'release_date': '2018-04-06',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/7GEzhoTiqcPYkOprWQu581'},
 {'album_id': '5rbJtzuXtpIP0Ykk7ewIit',
  'name': '7',
  'release_date': '2018-09-14',
  'total_tracks': 27,
  'url': 'https://open.spotify.com/album/5rbJtzuXtpIP0Ykk7ewIit'},
 {'album_id': '5VdyJkLe3yvOs0l4xXbWp0',
  'name': '17',
  'release_date': '2017-08-25',
  'total_tracks': 11,
  'url': 'https://open.spotify.com/album/5VdyJkLe3yvOs0l4xXbWp0'},
 {'album_id': '1ATL5GLyefJaxhQzSPVrLX',
  'name': 'Scorpion',
  'release_date': '2018-06-29',
  'total_tracks': 25,
  'url': 'https://open.spotify.com/album/1ATL5GLyefJaxhQzSPVrLX'},
 {'album_id': '5kprdYds6oZb4iSldfflOT',
  'name': 'Vibras',
  'release_date': '2018-05-25',
  'total_tracks': 14,
  'url': 'https://open.spotify.com/album/5kprdYds6oZb4iSldfflOT'},
 {'album_id': '5dL5RSd455FewNptPgtBTS',
  'name': 'Goodbye (feat. Nicki Minaj & Willy William)',
  'release_date': '2018-08-24',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/5dL5RSd455FewNptPgtBTS'},
 {'album_id': '3HNnxK7NgLXbDoxRZxNWiR',
  'name': 'Kamikaze',
  'release_date': '2018-08-31',
  'total_tracks': 13,
  'url': 'https://open.spotify.com/album/3HNnxK7NgLXbDoxRZxNWiR'},
 {'album_id': '3tx8gQqWbGwqIGZHqDNrGe',
  'name': 'Sweetener',
  'release_date': '2018-08-17',
  'total_tracks': 15,
  'url': 'https://open.spotify.com/album/3tx8gQqWbGwqIGZHqDNrGe'},
 {'album_id': '0JcW7yCW3Qj8uMfzO2lUDb',
  'name': 'Happy Now',
  'release_date': '2018-07-18',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/0JcW7yCW3Qj8uMfzO2lUDb'},
 {'album_id': '6trNtQUgC8cgbWcqoMYkOR',
  'name': 'beerbongs & bentleys',
  'release_date': '2018-04-27',
  'total_tracks': 18,
  'url': 'https://open.spotify.com/album/6trNtQUgC8cgbWcqoMYkOR'},
 {'album_id': '6hAxqfWO3xDGzjs8yad1pB',
  'name': 'Sin Pijama',
  'release_date': '2018-04-20',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/6hAxqfWO3xDGzjs8yad1pB'},
 {'album_id': '3qowbCeEsKLpcHDgZiPMad',
  'name': 'God is a woman',
  'release_date': '2018-07-13',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/3qowbCeEsKLpcHDgZiPMad'},
 {'album_id': '4hlAdqONoJhkjf8u9XMjQr',
  'name': 'All Falls Down (feat. Juliander)',
  'release_date': '2017-10-27',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/4hlAdqONoJhkjf8u9XMjQr'},
 {'album_id': '2AkKk7DFnT2IV1gPcq7RCQ',
  'name': 'no tears left to cry',
  'release_date': '2018-04-20',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/2AkKk7DFnT2IV1gPcq7RCQ'},
 {'album_id': '5pFVq0CSfbMMk6s4Kv256T',
  'name': 'Mad Love',
  'release_date': '2018-02-15',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/5pFVq0CSfbMMk6s4Kv256T'},
 {'album_id': '47oyrKaeobswT4T8zyaxdM',
  'name': 'Kids in Love',
  'release_date': '2017-11-03',
  'total_tracks': 9,
  'url': 'https://open.spotify.com/album/47oyrKaeobswT4T8zyaxdM'},
 {'album_id': '75iQSBSaztFIAun9qLLCnb',
  'name': 'Girls Like You (feat. Cardi B)',
  'release_date': '2018-05-30',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/75iQSBSaztFIAun9qLLCnb'},
 {'album_id': '6oSxSPOg7Kuitjt2zwP7sU',
  'name': '2002',
  'release_date': '2018-04-19',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/6oSxSPOg7Kuitjt2zwP7sU'},
 {'album_id': '2HpvpeGTBWdzBqKGLTLd3H',
  'name': 'Sun In Our Eyes',
  'release_date': '2018-07-12',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/2HpvpeGTBWdzBqKGLTLd3H'},
 {'album_id': '6c5gDwB7Xo58thk2vap4Ch',
  'name': 'Nevermind',
  'release_date': '2017-06-30',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/6c5gDwB7Xo58thk2vap4Ch'},
 {'album_id': '4CEAev7neETRdqBFtzA8B9',
  'name': 'Love Lies',
  'release_date': '2018-02-14',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/4CEAev7neETRdqBFtzA8B9'},
 {'album_id': '4sqrDaJcbCIo6aeqO26maj',
  'name': "Don't Leave Me Alone (feat. Anne-Marie)",
  'release_date': '2018-07-26',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/4sqrDaJcbCIo6aeqO26maj'},
 {'album_id': '2sjjFDjZSCYD5eBCsi0fDW',
  'name': 'These Days (feat. Jess Glynne, Macklemore & Dan Caplen)',
  'release_date': '2018-01-19',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/2sjjFDjZSCYD5eBCsi0fDW'},
 {'album_id': '1Kix2Ho3LgJI4tmtcFdNr8',
  'name': 'Fuego',
  'release_date': '2018-05-19',
  'total_tracks': 2,
  'url': 'https://open.spotify.com/album/1Kix2Ho3LgJI4tmtcFdNr8'},
 {'album_id': '0LOJHhz9ybWLVMLucHYtCe',
  'name': 'REMEDY',
  'release_date': '2018-08-31',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/0LOJHhz9ybWLVMLucHYtCe'},
 {'album_id': '64WDoAGyTcPlSIFAiSDsB0',
  'name': 'Darkside',
  'release_date': '2018-07-27',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/64WDoAGyTcPlSIFAiSDsB0'},
 {'album_id': '4Y6jkhla5dLnq9vfPI7gmX',
  'name': 'Zooted (feat. French Montana & Farruko)',
  'release_date': '2018-07-20',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/4Y6jkhla5dLnq9vfPI7gmX'},
 {'album_id': '2sBB17RXTamvj7Ncps15AK',
  'name': 'lovely (with Khalid)',
  'release_date': '2018-04-19',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/2sBB17RXTamvj7Ncps15AK'},
 {'album_id': '1XQ6XbZ6ZM1V5iEtWlYDeH',
  'name': 'Ocean (feat. Khalid)',
  'release_date': '2018-06-15',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/1XQ6XbZ6ZM1V5iEtWlYDeH'},
 {'album_id': '5rbJtzuXtpIP0Ykk7ewIit',
  'name': '7',
  'release_date': '2018-09-14',
  'total_tracks': 27,
  'url': 'https://open.spotify.com/album/5rbJtzuXtpIP0Ykk7ewIit'},
 {'album_id': '1GUfof1gHsqYjoHFym3aim',
  'name': 'High On Life (feat. Bonn)',
  'release_date': '2018-07-29',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/1GUfof1gHsqYjoHFym3aim'},
 {'album_id': '4Mli74klkx5jMSZlqYa3Lh',
  'name': 'Sick Boy',
  'release_date': '2018-04-20',
  'total_tracks': 4,
  'url': 'https://open.spotify.com/album/4Mli74klkx5jMSZlqYa3Lh'},
 {'album_id': '6KlKprVgLbkUTtynww6MQh',
  'name': 'Bed (feat. Ariana Grande)',
  'release_date': '2018-06-14',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/6KlKprVgLbkUTtynww6MQh'},
 {'album_id': '4UsjjAKbtKzmgEz2pGbv6P',
  'name': 'Right Now',
  'release_date': '2018-08-24',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/4UsjjAKbtKzmgEz2pGbv6P'},
 {'album_id': '31J0UqxAkl9utyC0L59Mae',
  'name': 'Born To Be Yours',
  'release_date': '2018-06-15',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/31J0UqxAkl9utyC0L59Mae'},
 {'album_id': '1D8u1ccrRXyFMOGTEXTgTX',
  'name': 'The Middle',
  'release_date': '2018-01-23',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/1D8u1ccrRXyFMOGTEXTgTX'},
 {'album_id': '16Qs4jnIyXe7jprnMNRddy',
  'name': 'Youngblood',
  'release_date': '2018-04-12',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/16Qs4jnIyXe7jprnMNRddy'},
 {'album_id': '56mP4ipdgYC7y4CJnHC0Vl',
  'name': 'Like I Love You',
  'release_date': '2018-09-14',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/56mP4ipdgYC7y4CJnHC0Vl'},
 {'album_id': '01sfgrNbnnPUEyz6GZYlt9',
  'name': 'Dua Lipa (Deluxe)',
  'release_date': '2017-06-02',
  'total_tracks': 17,
  'url': 'https://open.spotify.com/album/01sfgrNbnnPUEyz6GZYlt9'},
 {'album_id': '1VZCKNtlvWJSejzfZZs9xB',
  'name': "Don't Hide",
  'release_date': '2018-06-29',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/1VZCKNtlvWJSejzfZZs9xB'},
 {'album_id': '6nDktVazQbm8o43JqUnN5c',
  'name': 'Just Wanna Love You (feat. J. Balvin)',
  'release_date': '2018-09-14',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/6nDktVazQbm8o43JqUnN5c'},
 {'album_id': '4Hwj8MyVYpdLEGKOFjVjQF',
  'name': 'Want To',
  'release_date': '2018-09-06',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/4Hwj8MyVYpdLEGKOFjVjQF'},
 {'album_id': '3wX49A4zAxAhQJ0uN5FLsl',
  'name': 'Audio',
  'release_date': '2018-05-10',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/3wX49A4zAxAhQJ0uN5FLsl'},
 {'album_id': '09uJvEy1F5GwvazqSQcYyB',
  'name': 'Just Got Paid',
  'release_date': '2018-09-07',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/09uJvEy1F5GwvazqSQcYyB'},
 {'album_id': '1L5GP3Zuu7BvI81OJ0VkpT',
  'name': 'Familiar',
  'release_date': '2018-04-20',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/1L5GP3Zuu7BvI81OJ0VkpT'},
 {'album_id': '1XQ6XbZ6ZM1V5iEtWlYDeH',
  'name': 'Ocean (feat. Khalid)',
  'release_date': '2018-06-15',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/1XQ6XbZ6ZM1V5iEtWlYDeH'},
 {'album_id': '31J0UqxAkl9utyC0L59Mae',
  'name': 'Born To Be Yours',
  'release_date': '2018-06-15',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/31J0UqxAkl9utyC0L59Mae'},
 {'album_id': '6KlKprVgLbkUTtynww6MQh',
  'name': 'Bed (feat. Ariana Grande)',
  'release_date': '2018-06-14',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/6KlKprVgLbkUTtynww6MQh'},
 {'album_id': '1ATL5GLyefJaxhQzSPVrLX',
  'name': 'Scorpion',
  'release_date': '2018-06-29',
  'total_tracks': 25,
  'url': 'https://open.spotify.com/album/1ATL5GLyefJaxhQzSPVrLX'},
 {'album_id': '3N7eWDCvfWv34xWNohdHjO',
  'name': 'Back To You (From 13 Reasons Why – Season 2 Soundtrack)',
  'release_date': '2018-05-10',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/3N7eWDCvfWv34xWNohdHjO'},
 {'album_id': '0PypWtpDDSDP0IEg7LuoIw',
  'name': 'One Day (feat. Ryan Tedder)',
  'release_date': '2018-07-27',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/0PypWtpDDSDP0IEg7LuoIw'},
 {'album_id': '6c5gDwB7Xo58thk2vap4Ch',
  'name': 'Nevermind',
  'release_date': '2017-06-30',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/6c5gDwB7Xo58thk2vap4Ch'},
 {'album_id': '4DmPCrBlJGedbs6GW7EQ1m',
  'name': 'Only You (with Little Mix)',
  'release_date': '2018-06-22',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/4DmPCrBlJGedbs6GW7EQ1m'},
 {'album_id': '6rVOUFV4qi8MgqF7na73rX',
  'name': 'Connection',
  'release_date': '2018-06-26',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/6rVOUFV4qi8MgqF7na73rX'},
 {'album_id': '50ztaMltoS9mN9fm8R3zcW',
  'name': 'Palo Santo (Deluxe)',
  'release_date': '2018-07-06',
  'total_tracks': 14,
  'url': 'https://open.spotify.com/album/50ztaMltoS9mN9fm8R3zcW'},
 {'album_id': '4TOkZvtqNpg5UHyGxCn0mS',
  'name': 'Expectations',
  'release_date': '2018-06-22',
  'total_tracks': 14,
  'url': 'https://open.spotify.com/album/4TOkZvtqNpg5UHyGxCn0mS'},
 {'album_id': '3mzHuQmDLVuecodQNKUd0T',
  'name': 'Growing Pains',
  'release_date': '2018-06-15',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/3mzHuQmDLVuecodQNKUd0T'},
 {'album_id': '43UPJEBgAwfuGufr9RsCJV',
  'name': 'Dance To This (feat. Ariana Grande)',
  'release_date': '2018-06-13',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/43UPJEBgAwfuGufr9RsCJV'},
 {'album_id': '6XMyDP1SroC2aCiLkKw5bA',
  'name': 'Too Much (feat. Timbaland)',
  'release_date': '2018-08-02',
  'total_tracks': 1,
  'url': 'https://open.spotify.com/album/6XMyDP1SroC2aCiLkKw5bA'},
 {'album_id': '15k99o4mZJ9mfpQGIOrZ45',
  'name': 'Summer Pack',
  'release_date': '2018-07-11',
  'total_tracks': 2,
  'url': 'https://open.spotify.com/album/15k99o4mZJ9mfpQGIOrZ45'},
 {'album_id': '4RpgjxgSxcRwGNuWnImneN',
  'name': '13 Reasons Why (Season 2)',
  'release_date': '2018-05-18',
  'total_tracks': 20,
  'url': 'https://open.spotify.com/album/4RpgjxgSxcRwGNuWnImneN'}]

In [70]:
data['items'][0]

{'added_at': '2023-02-10T09:38:05Z',
 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/'},
  'href': 'https://api.spotify.com/v1/users/',
  'id': '',
  'type': 'user',
  'uri': 'spotify:user:'},
 'is_local': False,
 'primary_color': None,
 'track': {'album': {'album_type': 'single',
   'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5YGY8feqx7naU7z4HrwZM6'},
     'href': 'https://api.spotify.com/v1/artists/5YGY8feqx7naU7z4HrwZM6',
     'id': '5YGY8feqx7naU7z4HrwZM6',
     'name': 'Miley Cyrus',
     'type': 'artist',
     'uri': 'spotify:artist:5YGY8feqx7naU7z4HrwZM6'}],
   'available_markets': ['AD',
    'AE',
    'AG',
    'AL',
    'AM',
    'AO',
    'AR',
    'AT',
    'AU',
    'AZ',
    'BA',
    'BB',
    'BD',
    'BE',
    'BF',
    'BG',
    'BH',
    'BI',
    'BJ',
    'BN',
    'BO',
    'BR',
    'BS',
    'BT',
    'BW',
    'BY',
    'BZ',
    'CA',
    'CD',
    'CG',
    'CH',
    'CI',
    'CL',
    'CM',
    'CO',
    'CR',
    'CV',
    'CW',
    'CY',
    'CZ',
    'DE',
    'DJ',
    'DK',
    'DM',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'ES',
    'ET',
    'FI',
    'FJ',
    'FM',
    'FR',
    'GA',
    'GB',
    'GD',
    'GE',
    'GH',
    'GM',
    'GN',
    'GQ',
    'GR',
    'GT',
    'GW',
    'GY',
    'HK',
    'HN',
    'HR',
    'HT',
    'HU',
    'ID',
    'IE',
    'IL',
    'IN',
    'IQ',
    'IS',
    'IT',
    'JM',
    'JO',
    'JP',
    'KE',
    'KG',
    'KH',
    'KI',
    'KM',
    'KN',
    'KR',
    'KW',
    'KZ',
    'LA',
    'LB',
    'LC',
    'LI',
    'LK',
    'LR',
    'LS',
    'LT',
    'LU',
    'LV',
    'LY',
    'MA',
    'MC',
    'MD',
    'ME',
    'MG',
    'MH',
    'MK',
    'ML',
    'MN',
    'MO',
    'MR',
    'MT',
    'MU',
    'MV',
    'MW',
    'MX',
    'MY',
    'MZ',
    'NA',
    'NE',
    'NG',
    'NI',
    'NL',
    'NO',
    'NP',
    'NR',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PG',
    'PH',
    'PK',
    'PL',
    'PS',
    'PT',
    'PW',
    'PY',
    'QA',
    'RO',
    'RS',
    'RW',
    'SA',
    'SB',
    'SC',
    'SE',
    'SG',
    'SI',
    'SK',
    'SL',
    'SM',
    'SN',
    'SR',
    'ST',
    'SV',
    'SZ',
    'TD',
    'TG',
    'TH',
    'TJ',
    'TL',
    'TN',
    'TO',
    'TR',
    'TT',
    'TV',
    'TW',
    'TZ',
    'UA',
    'UG',
    'US',
    'UY',
    'UZ',
    'VC',
    'VE',
    'VN',
    'VU',
    'WS',
    'XK',
    'ZA',
    'ZM',
    'ZW'],
   'external_urls': {'spotify': 'https://open.spotify.com/album/7I0tjwFtxUwBC1vgyeMAax'},
   'href': 'https://api.spotify.com/v1/albums/7I0tjwFtxUwBC1vgyeMAax',
   'id': '7I0tjwFtxUwBC1vgyeMAax',
   'images': [{'height': 640,
     'url': 'https://i.scdn.co/image/ab67616d0000b273f429549123dbe8552764ba1d',
     'width': 640},
    {'height': 300,
     'url': 'https://i.scdn.co/image/ab67616d00001e02f429549123dbe8552764ba1d',
     'width': 300},
    {'height': 64,
     'url': 'https://i.scdn.co/image/ab67616d00004851f429549123dbe8552764ba1d',
     'width': 64}],
   'name': 'Flowers',
   'release_date': '2023-01-13',
   'release_date_precision': 'day',
   'total_tracks': 1,
   'type': 'album',
   'uri': 'spotify:album:7I0tjwFtxUwBC1vgyeMAax'},
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5YGY8feqx7naU7z4HrwZM6'},
    'href': 'https://api.spotify.com/v1/artists/5YGY8feqx7naU7z4HrwZM6',
    'id': '5YGY8feqx7naU7z4HrwZM6',
    'name': 'Miley Cyrus',
    'type': 'artist',
    'uri': 'spotify:artist:5YGY8feqx7naU7z4HrwZM6'}],
  'available_markets': ['AD',
   'AE',
   'AG',
   'AL',
   'AM',
   'AO',
   'AR',
   'AT',
   'AU',
   'AZ',
   'BA',
   'BB',
   'BD',
   'BE',
   'BF',
   'BG',
   'BH',
   'BI',
   'BJ',
   'BN',
   'BO',
   'BR',
   'BS',
   'BT',
   'BW',
   'BY',
   'BZ',
   'CA',
   'CD',
   'CG',
   'CH',
   'CI',
   'CL',
   'CM',
   'CO',
   'CR',
   'CV',
   'CW',
   'CY',
   'CZ',
   'DE',
   'DJ',
   'DK',
   'DM',
   'DO',
   'DZ',
   'EC',
   'EE',
   'EG',
   'ES',
   'ET',
   'FI',
   'FJ',
   'FM',
   'FR',
   'GA',
   'GB',
   'GD',
   'GE',
   'GH',
   'GM',
   'GN',
   'GQ',
   'GR',
   'GT',
   'GW',
   'GY',
   'HK',
   'HN',
   'HR',
   'HT',
   'HU',
   'ID',
   'IE',
   'IL',
   'IN',
   'IQ',
   'IS',
   'IT',
   'JM',
   'JO',
   'JP',
   'KE',
   'KG',
   'KH',
   'KI',
   'KM',
   'KN',
   'KR',
   'KW',
   'KZ',
   'LA',
   'LB',
   'LC',
   'LI',
   'LK',
   'LR',
   'LS',
   'LT',
   'LU',
   'LV',
   'LY',
   'MA',
   'MC',
   'MD',
   'ME',
   'MG',
   'MH',
   'MK',
   'ML',
   'MN',
   'MO',
   'MR',
   'MT',
   'MU',
   'MV',
   'MW',
   'MX',
   'MY',
   'MZ',
   'NA',
   'NE',
   'NG',
   'NI',
   'NL',
   'NO',
   'NP',
   'NR',
   'NZ',
   'OM',
   'PA',
   'PE',
   'PG',
   'PH',
   'PK',
   'PL',
   'PS',
   'PT',
   'PW',
   'PY',
   'QA',
   'RO',
   'RS',
   'RW',
   'SA',
   'SB',
   'SC',
   'SE',
   'SG',
   'SI',
   'SK',
   'SL',
   'SM',
   'SN',
   'SR',
   'ST',
   'SV',
   'SZ',
   'TD',
   'TG',
   'TH',
   'TJ',
   'TL',
   'TN',
   'TO',
   'TR',
   'TT',
   'TV',
   'TW',
   'TZ',
   'UA',
   'UG',
   'US',
   'UY',
   'UZ',
   'VC',
   'VE',
   'VN',
   'VU',
   'WS',
   'XK',
   'ZA',
   'ZM',
   'ZW'],
  'disc_number': 1,
  'duration_ms': 200454,
  'episode': False,
  'explicit': False,
  'external_ids': {'isrc': 'USSM12209777'},
  'external_urls': {'spotify': 'https://open.spotify.com/track/0yLdNVWF3Srea0uzk55zFn'},
  'href': 'https://api.spotify.com/v1/tracks/0yLdNVWF3Srea0uzk55zFn',
  'id': '0yLdNVWF3Srea0uzk55zFn',
  'is_local': False,
  'name': 'Flowers',
  'popularity': 100,
  'preview_url': 'https://p.scdn.co/mp3-preview/f2857681239dee871da7055d2f725ea6dcd1b4d8?cid=cad932832b224420829e29749598ef3f',
  'track': True,
  'track_number': 1,
  'type': 'track',
  'uri': 'spotify:track:0yLdNVWF3Srea0uzk55zFn'},
 'video_thumbnail': {'url': None}}

In [196]:
data['items'][0]['track']

{'preview_url': None,
 'available_markets': ['AR',
  'AU',
  'AT',
  'BE',
  'BO',
  'BR',
  'BG',
  'CA',
  'CL',
  'CO',
  'CR',
  'CY',
  'CZ',
  'DK',
  'DO',
  'DE',
  'EC',
  'EE',
  'SV',
  'FI',
  'FR',
  'GR',
  'GT',
  'HN',
  'HK',
  'HU',
  'IS',
  'IE',
  'IT',
  'LV',
  'LT',
  'LU',
  'MY',
  'MT',
  'MX',
  'NL',
  'NZ',
  'NI',
  'NO',
  'PA',
  'PY',
  'PE',
  'PH',
  'PL',
  'PT',
  'SG',
  'SK',
  'ES',
  'SE',
  'CH',
  'TW',
  'TR',
  'UY',
  'US',
  'GB',
  'AD',
  'LI',
  'MC',
  'ID',
  'JP',
  'TH',
  'VN',
  'RO',
  'IL',
  'ZA',
  'SA',
  'AE',
  'BH',
  'QA',
  'OM',
  'KW',
  'EG',
  'MA',
  'DZ',
  'TN',
  'LB',
  'JO',
  'PS',
  'IN',
  'KZ',
  'MD',
  'UA',
  'AL',
  'BA',
  'HR',
  'ME',
  'MK',
  'RS',
  'SI',
  'KR',
  'BD',
  'PK',
  'LK',
  'GH',
  'KE',
  'NG',
  'TZ',
  'UG',
  'AG',
  'AM',
  'BS',
  'BB',
  'BZ',
  'BT',
  'BW',
  'CV',
  'CW',
  'DM',
  'FJ',
  'GM',
  'GE',
  'GD',
  'GW',
  'GY',
  'HT',
  'JM',
  'KI',
  'LS',
  'LR',
  'MW',
  'MV',
  'ML',
  'MH',
  'FM',
  'NA',
  'NR',
  'NE',
  'PW',
  'PG',
  'WS',
  'SM',
  'ST',
  'SN',
  'SC',
  'SL',
  'SB',
  'KN',
  'LC',
  'VC',
  'SR',
  'TL',
  'TO',
  'TT',
  'TV',
  'VU',
  'AZ',
  'BI',
  'KH',
  'CM',
  'TD',
  'KM',
  'GQ',
  'SZ',
  'GA',
  'GN',
  'KG',
  'LA',
  'MO',
  'MR',
  'MN',
  'RW',
  'TG',
  'ZW',
  'BJ',
  'MG',
  'MU',
  'MZ',
  'AO',
  'CI',
  'DJ',
  'ZM',
  'CD',
  'CG',
  'IQ',
  'LY',
  'TJ',
  'VE',
  'ET',
  'XK'],
 'explicit': True,
 'type': 'track',
 'episode': False,
 'track': True,
 'album': {'available_markets': ['AR',
   'AU',
   'AT',
   'BE',
   'BO',
   'BR',
   'BG',
   'CA',
   'CL',
   'CO',
   'CR',
   'CY',
   'CZ',
   'DK',
   'DO',
   'DE',
   'EC',
   'EE',
   'SV',
   'FI',
   'FR',
   'GR',
   'GT',
   'HN',
   'HK',
   'HU',
   'IS',
   'IE',
   'IT',
   'LV',
   'LT',
   'LU',
   'MY',
   'MT',
   'MX',
   'NL',
   'NZ',
   'NI',
   'NO',
   'PA',
   'PY',
   'PE',
   'PH',
   'PL',
   'PT',
   'SG',
   'SK',
   'ES',
   'SE',
   'CH',
   'TW',
   'TR',
   'UY',
   'US',
   'GB',
   'AD',
   'LI',
   'MC',
   'ID',
   'JP',
   'TH',
   'VN',
   'RO',
   'IL',
   'ZA',
   'SA',
   'AE',
   'BH',
   'QA',
   'OM',
   'KW',
   'EG',
   'MA',
   'DZ',
   'TN',
   'LB',
   'JO',
   'PS',
   'IN',
   'KZ',
   'MD',
   'UA',
   'AL',
   'BA',
   'HR',
   'ME',
   'MK',
   'RS',
   'SI',
   'KR',
   'BD',
   'PK',
   'LK',
   'GH',
   'KE',
   'NG',
   'TZ',
   'UG',
   'AG',
   'AM',
   'BS',
   'BB',
   'BZ',
   'BT',
   'BW',
   'CV',
   'CW',
   'DM',
   'FJ',
   'GM',
   'GE',
   'GD',
   'GW',
   'GY',
   'HT',
   'JM',
   'KI',
   'LS',
   'LR',
   'MW',
   'MV',
   'ML',
   'MH',
   'FM',
   'NA',
   'NR',
   'NE',
   'PW',
   'PG',
   'WS',
   'SM',
   'ST',
   'SN',
   'SC',
   'SL',
   'SB',
   'KN',
   'LC',
   'VC',
   'SR',
   'TL',
   'TO',
   'TT',
   'TV',
   'VU',
   'AZ',
   'BI',
   'KH',
   'CM',
   'TD',
   'KM',
   'GQ',
   'SZ',
   'GA',
   'GN',
   'KG',
   'LA',
   'MO',
   'MR',
   'MN',
   'RW',
   'TG',
   'ZW',
   'BJ',
   'MG',
   'MU',
   'MZ',
   'AO',
   'CI',
   'DJ',
   'ZM',
   'CD',
   'CG',
   'IQ',
   'LY',
   'TJ',
   'VE',
   'ET',
   'XK'],
  'type': 'album',
  'album_type': 'single',
  'href': 'https://api.spotify.com/v1/albums/185Tm1g5U7eMOrm3m9SQUh',
  'id': '185Tm1g5U7eMOrm3m9SQUh',
  'images': [{'height': 640,
    'url': 'https://i.scdn.co/image/ab67616d0000b273b6d544387b04e1d1a5f7926c',
    'width': 640},
   {'height': 300,
    'url': 'https://i.scdn.co/image/ab67616d00001e02b6d544387b04e1d1a5f7926c',
    'width': 300},
   {'height': 64,
    'url': 'https://i.scdn.co/image/ab67616d00004851b6d544387b04e1d1a5f7926c',
    'width': 64}],
  'name': 'I Love It',
  'release_date': '2018-09-07',
  'release_date_precision': 'day',
  'uri': 'spotify:album:185Tm1g5U7eMOrm3m9SQUh',
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x'},
    'href': 'https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x',
    'id': '5K4W6rqBFWDnAN6FQUkS6x',
    'name': 'Kanye West',
    'type': 'artist',
    'uri': 'spotify:artist:5K4W6rqBFWDnAN6FQUkS6x'},
   {'external_urls': {'spotify': 'https://open.spotify.com/artist/3wyVrVrFCkukjdVIdirGVY'},
    'href': 'https://api.spotify.com/v1/artists/3wyVrVrFCkukjdVIdirGVY',
    'id': '3wyVrVrFCkukjdVIdirGVY',
    'name': 'Lil Pump',
    'type': 'artist',
    'uri': 'spotify:artist:3wyVrVrFCkukjdVIdirGVY'}],
  'external_urls': {'spotify': 'https://open.spotify.com/album/185Tm1g5U7eMOrm3m9SQUh'},
  'total_tracks': 1},
 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x'},
   'href': 'https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x',
   'id': '5K4W6rqBFWDnAN6FQUkS6x',
   'name': 'Kanye West',
   'type': 'artist',
   'uri': 'spotify:artist:5K4W6rqBFWDnAN6FQUkS6x'},
  {'external_urls': {'spotify': 'https://open.spotify.com/artist/3wyVrVrFCkukjdVIdirGVY'},
   'href': 'https://api.spotify.com/v1/artists/3wyVrVrFCkukjdVIdirGVY',
   'id': '3wyVrVrFCkukjdVIdirGVY',
   'name': 'Lil Pump',
   'type': 'artist',
   'uri': 'spotify:artist:3wyVrVrFCkukjdVIdirGVY'}],
 'disc_number': 1,
 'track_number': 1,
 'duration_ms': 127946,
 'external_ids': {'isrc': 'USUM71814031'},
 'external_urls': {'spotify': 'https://open.spotify.com/track/4S8d14HvHb70ImctNgVzQQ'},
 'href': 'https://api.spotify.com/v1/tracks/4S8d14HvHb70ImctNgVzQQ',
 'id': '4S8d14HvHb70ImctNgVzQQ',
 'name': 'I Love It (& Lil Pump)',
 'popularity': 69,
 'uri': 'spotify:track:4S8d14HvHb70ImctNgVzQQ',
 'is_local': False}

In [200]:
data['items'][0]['track']['artists']

[{'external_urls': {'spotify': 'https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x'},
  'href': 'https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x',
  'id': '5K4W6rqBFWDnAN6FQUkS6x',
  'name': 'Kanye West',
  'type': 'artist',
  'uri': 'spotify:artist:5K4W6rqBFWDnAN6FQUkS6x'},
 {'external_urls': {'spotify': 'https://open.spotify.com/artist/3wyVrVrFCkukjdVIdirGVY'},
  'href': 'https://api.spotify.com/v1/artists/3wyVrVrFCkukjdVIdirGVY',
  'id': '3wyVrVrFCkukjdVIdirGVY',
  'name': 'Lil Pump',
  'type': 'artist',
  'uri': 'spotify:artist:3wyVrVrFCkukjdVIdirGVY'}]

In [202]:
artist_list = []
for row in data['items']:
    for key, value in row.items():
        if key == "track":
            for artist in value['artists']:
                artist_dict = {'artist_id':artist['id'], 'artist_name':artist['name'], 'external_url': artist['href']}
                artist_list.append(artist_dict)

In [204]:
artist_list

[{'artist_id': '5K4W6rqBFWDnAN6FQUkS6x',
  'artist_name': 'Kanye West',
  'external_url': 'https://api.spotify.com/v1/artists/5K4W6rqBFWDnAN6FQUkS6x'},
 {'artist_id': '3wyVrVrFCkukjdVIdirGVY',
  'artist_name': 'Lil Pump',
  'external_url': 'https://api.spotify.com/v1/artists/3wyVrVrFCkukjdVIdirGVY'},
 {'artist_id': '7dGJo4pcD2V6oG8kP0tJRR',
  'artist_name': 'Eminem',
  'external_url': 'https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR'},
 {'artist_id': '6C1ohJrd5VydigQtaGy5Wa',
  'artist_name': 'Joyner Lucas',
  'external_url': 'https://api.spotify.com/v1/artists/6C1ohJrd5VydigQtaGy5Wa'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '5CiGnKThu5ctn9pBxv7DGa',
  'artist_name': 'benny blanco',
  'external_url': 'https://api.spotify.com/v1/artists/5CiGnKThu5ctn9pBxv7DGa'},
 {'artist_id': '26VFTg2z8YR0cCuwLzESi2',
  'artist_name': 'Halsey',
  'external_url': 'https://api.spotify.com/v1/artists/26VFTg2z8YR0cCuwLzESi2'},
 {'artist_id': '6LuN9FCkKOj5PcnpouEgny',
  'artist_name': 'Khalid',
  'external_url': 'https://api.spotify.com/v1/artists/6LuN9FCkKOj5PcnpouEgny'},
 {'artist_id': '64KEffDW9EtZ1y2vBYgq8T',
  'artist_name': 'Marshmello',
  'external_url': 'https://api.spotify.com/v1/artists/64KEffDW9EtZ1y2vBYgq8T'},
 {'artist_id': '7EQ0qTo7fWT7DPxmxtSYEc',
  'artist_name': 'Bastille',
  'external_url': 'https://api.spotify.com/v1/artists/7EQ0qTo7fWT7DPxmxtSYEc'},
 {'artist_id': '7CajNmpbOovFoOoasH2HaY',
  'artist_name': 'Calvin Harris',
  'external_url': 'https://api.spotify.com/v1/artists/7CajNmpbOovFoOoasH2HaY'},
 {'artist_id': '2wY79sveU1sp5g7SokKOiI',
  'artist_name': 'Sam Smith',
  'external_url': 'https://api.spotify.com/v1/artists/2wY79sveU1sp5g7SokKOiI'},
 {'artist_id': '3KedxarmBCyFBevnqQHy3P',
  'artist_name': 'Jessie Reyez',
  'external_url': 'https://api.spotify.com/v1/artists/3KedxarmBCyFBevnqQHy3P'},
 {'artist_id': '3v6Ji4uoWtKRkhuDUaxi9n',
  'artist_name': 'Dynoro',
  'external_url': 'https://api.spotify.com/v1/artists/3v6Ji4uoWtKRkhuDUaxi9n'},
 {'artist_id': '1OAjDaKgg00KCUYqDe68un',
  'artist_name': "Gigi D'Agostino",
  'external_url': 'https://api.spotify.com/v1/artists/1OAjDaKgg00KCUYqDe68un'},
 {'artist_id': '0Y5tJX1MQlPlqiwlOH1tJY',
  'artist_name': 'Travis Scott',
  'external_url': 'https://api.spotify.com/v1/artists/0Y5tJX1MQlPlqiwlOH1tJY'},
 {'artist_id': '04gDigrS5kc9YWfZHwBETP',
  'artist_name': 'Maroon 5',
  'external_url': 'https://api.spotify.com/v1/artists/04gDigrS5kc9YWfZHwBETP'},
 {'artist_id': '4kYSro6naA4h99UJvo89HB',
  'artist_name': 'Cardi B',
  'external_url': 'https://api.spotify.com/v1/artists/4kYSro6naA4h99UJvo89HB'},
 {'artist_id': '4MCBfE4596Uoi2O4DtmEMz',
  'artist_name': 'Juice WRLD',
  'external_url': 'https://api.spotify.com/v1/artists/4MCBfE4596Uoi2O4DtmEMz'},
 {'artist_id': '7gZfnEnfiaHzxARJ2LeXrf',
  'artist_name': '6ix9ine',
  'external_url': 'https://api.spotify.com/v1/artists/7gZfnEnfiaHzxARJ2LeXrf'},
 {'artist_id': '0hCNtLu0JehylgoiP8L4Gh',
  'artist_name': 'Nicki Minaj',
  'external_url': 'https://api.spotify.com/v1/artists/0hCNtLu0JehylgoiP8L4Gh'},
 {'artist_id': '3CbYyyd8wH3RT6t0jwpdzC',
  'artist_name': 'Murda Beatz',
  'external_url': 'https://api.spotify.com/v1/artists/3CbYyyd8wH3RT6t0jwpdzC'},
 {'artist_id': '2kCcBybjl3SAtIcwdWpUe3',
  'artist_name': 'Lil Peep',
  'external_url': 'https://api.spotify.com/v1/artists/2kCcBybjl3SAtIcwdWpUe3'},
 {'artist_id': '15UsOTVnJzReFVN1VCnxy4',
  'artist_name': 'XXXTENTACION',
  'external_url': 'https://api.spotify.com/v1/artists/15UsOTVnJzReFVN1VCnxy4'},
 {'artist_id': '3QSQFmccmX81fWCUSPTS7y',
  'artist_name': 'Dean Lewis',
  'external_url': 'https://api.spotify.com/v1/artists/3QSQFmccmX81fWCUSPTS7y'},
 {'artist_id': '4O15NlyKLIASxsJ0PrXPfz',
  'artist_name': 'Lil Uzi Vert',
  'external_url': 'https://api.spotify.com/v1/artists/4O15NlyKLIASxsJ0PrXPfz'},
 {'artist_id': '6LuN9FCkKOj5PcnpouEgny',
  'artist_name': 'Khalid',
  'external_url': 'https://api.spotify.com/v1/artists/6LuN9FCkKOj5PcnpouEgny'},
 {'artist_id': '15UsOTVnJzReFVN1VCnxy4',
  'artist_name': 'XXXTENTACION',
  'external_url': 'https://api.spotify.com/v1/artists/15UsOTVnJzReFVN1VCnxy4'},
 {'artist_id': '2X97ZAqRKRMYFIDqtvGgGc',
  'artist_name': 'Silk City',
  'external_url': 'https://api.spotify.com/v1/artists/2X97ZAqRKRMYFIDqtvGgGc'},
 {'artist_id': '6M2wZ9GZgrQXHCFfjv46we',
  'artist_name': 'Dua Lipa',
  'external_url': 'https://api.spotify.com/v1/artists/6M2wZ9GZgrQXHCFfjv46we'},
 {'artist_id': '3hv9jJF3adDNsBSIQDqcjp',
  'artist_name': 'Mark Ronson',
  'external_url': 'https://api.spotify.com/v1/artists/3hv9jJF3adDNsBSIQDqcjp'},
 {'artist_id': '5fMUXHkw8R8eOP2RNVYEZX',
  'artist_name': 'Diplo',
  'external_url': 'https://api.spotify.com/v1/artists/5fMUXHkw8R8eOP2RNVYEZX'},
 {'artist_id': '5LHRHt1k9lMyONurDHEdrp',
  'artist_name': 'Tyga',
  'external_url': 'https://api.spotify.com/v1/artists/5LHRHt1k9lMyONurDHEdrp'},
 {'artist_id': '4DdkRBBYG6Yk9Ka8tdJ9BW',
  'artist_name': 'Offset',
  'external_url': 'https://api.spotify.com/v1/artists/4DdkRBBYG6Yk9Ka8tdJ9BW'},
 {'artist_id': '0QHgL1lAIqAw0HtD7YldmP',
  'artist_name': 'DJ Khaled',
  'external_url': 'https://api.spotify.com/v1/artists/0QHgL1lAIqAw0HtD7YldmP'},
 {'artist_id': '1uNFoZAHBGtllmzznpCI3s',
  'artist_name': 'Justin Bieber',
  'external_url': 'https://api.spotify.com/v1/artists/1uNFoZAHBGtllmzznpCI3s'},
 {'artist_id': '0VRj0yCOv2FXJNP47XQnx5',
  'artist_name': 'Quavo',
  'external_url': 'https://api.spotify.com/v1/artists/0VRj0yCOv2FXJNP47XQnx5'},
 {'artist_id': '1anyVhU62p31KFi8MEzkbf',
  'artist_name': 'Chance the Rapper',
  'external_url': 'https://api.spotify.com/v1/artists/1anyVhU62p31KFi8MEzkbf'},
 {'artist_id': '4kYSro6naA4h99UJvo89HB',
  'artist_name': 'Cardi B',
  'external_url': 'https://api.spotify.com/v1/artists/4kYSro6naA4h99UJvo89HB'},
 {'artist_id': '4q3ewBCX7sLwd24euuV69X',
  'artist_name': 'Bad Bunny',
  'external_url': 'https://api.spotify.com/v1/artists/4q3ewBCX7sLwd24euuV69X'},
 {'artist_id': '1vyhD5VmyZ7KMfW5gqLgo5',
  'artist_name': 'J Balvin',
  'external_url': 'https://api.spotify.com/v1/artists/1vyhD5VmyZ7KMfW5gqLgo5'},
 {'artist_id': '53XhwfbYqKCa1cC15pYq2q',
  'artist_name': 'Imagine Dragons',
  'external_url': 'https://api.spotify.com/v1/artists/53XhwfbYqKCa1cC15pYq2q'},
 {'artist_id': '1i8SpTcr7yvPOmcqrbnVXY',
  'artist_name': 'Ozuna',
  'external_url': 'https://api.spotify.com/v1/artists/1i8SpTcr7yvPOmcqrbnVXY'},
 {'artist_id': '0tmwSHipWxN12fsoLcFU3B',
  'artist_name': 'Manuel Turizo',
  'external_url': 'https://api.spotify.com/v1/artists/0tmwSHipWxN12fsoLcFU3B'},
 {'artist_id': '7gZfnEnfiaHzxARJ2LeXrf',
  'artist_name': '6ix9ine',
  'external_url': 'https://api.spotify.com/v1/artists/7gZfnEnfiaHzxARJ2LeXrf'},
 {'artist_id': '2R21vXR83lH98kGeO99Y66',
  'artist_name': 'Anuel AA',
  'external_url': 'https://api.spotify.com/v1/artists/2R21vXR83lH98kGeO99Y66'},
 {'artist_id': '246dkjvS1zLTtiykXe5h60',
  'artist_name': 'Post Malone',
  'external_url': 'https://api.spotify.com/v1/artists/246dkjvS1zLTtiykXe5h60'},
 {'artist_id': '66CXWjxzNUsdJxJ2JdwvnR',
  'artist_name': 'Ariana Grande',
  'external_url': 'https://api.spotify.com/v1/artists/66CXWjxzNUsdJxJ2JdwvnR'},
 {'artist_id': '6t1gpxYbY8OlLA7D2RiikQ',
  'artist_name': 'Loud Luxury',
  'external_url': 'https://api.spotify.com/v1/artists/6t1gpxYbY8OlLA7D2RiikQ'},
 {'artist_id': '5uEeqYFuIChoWKy34jp8xE',
  'artist_name': 'Brando',
  'external_url': 'https://api.spotify.com/v1/artists/5uEeqYFuIChoWKy34jp8xE'},
 {'artist_id': '13y7CgLHjMVRMDqxdx0Xdo',
  'artist_name': 'Gucci Mane',
  'external_url': 'https://api.spotify.com/v1/artists/13y7CgLHjMVRMDqxdx0Xdo'},
 {'artist_id': '0du5cEVh5yTK9QJze8zA0C',
  'artist_name': 'Bruno Mars',
  'external_url': 'https://api.spotify.com/v1/artists/0du5cEVh5yTK9QJze8zA0C'},
 {'artist_id': '46SHBwWsqBkxI7EeeBEQG7',
  'artist_name': 'Kodak Black',
  'external_url': 'https://api.spotify.com/v1/artists/46SHBwWsqBkxI7EeeBEQG7'},
 {'artist_id': '66CXWjxzNUsdJxJ2JdwvnR',
  'artist_name': 'Ariana Grande',
  'external_url': 'https://api.spotify.com/v1/artists/66CXWjxzNUsdJxJ2JdwvnR'},
 {'artist_id': '1HBjj22wzbscIZ9sEb5dyf',
  'artist_name': 'Jonas Blue',
  'external_url': 'https://api.spotify.com/v1/artists/1HBjj22wzbscIZ9sEb5dyf'},
 {'artist_id': '1INuLZXjjVbcJRyWvD1iSq',
  'artist_name': 'Jack & Jack',
  'external_url': 'https://api.spotify.com/v1/artists/1INuLZXjjVbcJRyWvD1iSq'},
 {'artist_id': '5Rl15oVamLq7FbSb0NNBNy',
  'artist_name': '5 Seconds of Summer',
  'external_url': 'https://api.spotify.com/v1/artists/5Rl15oVamLq7FbSb0NNBNy'},
 {'artist_id': '6MDME20pz9RveH9rEXvrOM',
  'artist_name': 'Clean Bandit',
  'external_url': 'https://api.spotify.com/v1/artists/6MDME20pz9RveH9rEXvrOM'},
 {'artist_id': '6S2OmqARrzebs0tKUEyXyp',
  'artist_name': 'Demi Lovato',
  'external_url': 'https://api.spotify.com/v1/artists/6S2OmqARrzebs0tKUEyXyp'},
 {'artist_id': '15UsOTVnJzReFVN1VCnxy4',
  'artist_name': 'XXXTENTACION',
  'external_url': 'https://api.spotify.com/v1/artists/15UsOTVnJzReFVN1VCnxy4'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '5WUlDfRSoLAfcVSX1WnrxN',
  'artist_name': 'Sia',
  'external_url': 'https://api.spotify.com/v1/artists/5WUlDfRSoLAfcVSX1WnrxN'},
 {'artist_id': '5fMUXHkw8R8eOP2RNVYEZX',
  'artist_name': 'Diplo',
  'external_url': 'https://api.spotify.com/v1/artists/5fMUXHkw8R8eOP2RNVYEZX'},
 {'artist_id': '2feDdbD5araYcm6JhFHHw7',
  'artist_name': 'Labrinth',
  'external_url': 'https://api.spotify.com/v1/artists/2feDdbD5araYcm6JhFHHw7'},
 {'artist_id': '6IZ4ctovY9dl7bgHClAvKJ',
  'artist_name': 'LSD',
  'external_url': 'https://api.spotify.com/v1/artists/6IZ4ctovY9dl7bgHClAvKJ'},
 {'artist_id': '5hdhHgpxyniooUiQVaPxQ0',
  'artist_name': 'Nio Garcia',
  'external_url': 'https://api.spotify.com/v1/artists/5hdhHgpxyniooUiQVaPxQ0'},
 {'artist_id': '1fux65HMCBvfJHqlBc4Nno',
  'artist_name': 'Casper Magico',
  'external_url': 'https://api.spotify.com/v1/artists/1fux65HMCBvfJHqlBc4Nno'},
 {'artist_id': '4q3ewBCX7sLwd24euuV69X',
  'artist_name': 'Bad Bunny',
  'external_url': 'https://api.spotify.com/v1/artists/4q3ewBCX7sLwd24euuV69X'},
 {'artist_id': '1TtXnWcUs0FCkaZDPGYHdf',
  'artist_name': 'Darell',
  'external_url': 'https://api.spotify.com/v1/artists/1TtXnWcUs0FCkaZDPGYHdf'},
 {'artist_id': '1i8SpTcr7yvPOmcqrbnVXY',
  'artist_name': 'Ozuna',
  'external_url': 'https://api.spotify.com/v1/artists/1i8SpTcr7yvPOmcqrbnVXY'},
 {'artist_id': '1SupJlEpv7RS2tPNRaHViT',
  'artist_name': 'Nicky Jam',
  'external_url': 'https://api.spotify.com/v1/artists/1SupJlEpv7RS2tPNRaHViT'},
 {'artist_id': '2o5jDhtHVPhrJdv3cEQ99Z',
  'artist_name': 'Tiësto',
  'external_url': 'https://api.spotify.com/v1/artists/2o5jDhtHVPhrJdv3cEQ99Z'},
 {'artist_id': '5vQfv3s2Z2SRdPZKr82ABw',
  'artist_name': 'Dzeko',
  'external_url': 'https://api.spotify.com/v1/artists/5vQfv3s2Z2SRdPZKr82ABw'},
 {'artist_id': '0bdJZl7TDeiymDYzMJnVh2',
  'artist_name': 'Preme',
  'external_url': 'https://api.spotify.com/v1/artists/0bdJZl7TDeiymDYzMJnVh2'},
 {'artist_id': '246dkjvS1zLTtiykXe5h60',
  'artist_name': 'Post Malone',
  'external_url': 'https://api.spotify.com/v1/artists/246dkjvS1zLTtiykXe5h60'},
 {'artist_id': '7dGJo4pcD2V6oG8kP0tJRR',
  'artist_name': 'Eminem',
  'external_url': 'https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR'},
 {'artist_id': '4GvEc3ANtPPjt1ZJllr5Zl',
  'artist_name': 'Bazzi',
  'external_url': 'https://api.spotify.com/v1/artists/4GvEc3ANtPPjt1ZJllr5Zl'},
 {'artist_id': '4nDoRrQiYLoBzwC5BhVJzF',
  'artist_name': 'Camila Cabello',
  'external_url': 'https://api.spotify.com/v1/artists/4nDoRrQiYLoBzwC5BhVJzF'},
 {'artist_id': '2ysnwxxNtSgbb9t1m2Ur4j',
  'artist_name': 'George Ezra',
  'external_url': 'https://api.spotify.com/v1/artists/2ysnwxxNtSgbb9t1m2Ur4j'},
 {'artist_id': '7CajNmpbOovFoOoasH2HaY',
  'artist_name': 'Calvin Harris',
  'external_url': 'https://api.spotify.com/v1/artists/7CajNmpbOovFoOoasH2HaY'},
 {'artist_id': '6M2wZ9GZgrQXHCFfjv46we',
  'artist_name': 'Dua Lipa',
  'external_url': 'https://api.spotify.com/v1/artists/6M2wZ9GZgrQXHCFfjv46we'},
 {'artist_id': '1Cs0zKBU1kc0i8ypK3B9ai',
  'artist_name': 'David Guetta',
  'external_url': 'https://api.spotify.com/v1/artists/1Cs0zKBU1kc0i8ypK3B9ai'},
 {'artist_id': '1zNqDE7qDGCsyzJwohVaoX',
  'artist_name': 'Anne-Marie',
  'external_url': 'https://api.spotify.com/v1/artists/1zNqDE7qDGCsyzJwohVaoX'},
 {'artist_id': '15UsOTVnJzReFVN1VCnxy4',
  'artist_name': 'XXXTENTACION',
  'external_url': 'https://api.spotify.com/v1/artists/15UsOTVnJzReFVN1VCnxy4'},
 {'artist_id': '3TVXtAsR1Inumwj472S9r4',
  'artist_name': 'Drake',
  'external_url': 'https://api.spotify.com/v1/artists/3TVXtAsR1Inumwj472S9r4'},
 {'artist_id': '1vyhD5VmyZ7KMfW5gqLgo5',
  'artist_name': 'J Balvin',
  'external_url': 'https://api.spotify.com/v1/artists/1vyhD5VmyZ7KMfW5gqLgo5'},
 {'artist_id': '21451j1KhjAiaYKflxBjr1',
  'artist_name': 'Zion & Lennox',
  'external_url': 'https://api.spotify.com/v1/artists/21451j1KhjAiaYKflxBjr1'},
 {'artist_id': '07YZf4WDAMNwqr4jfgOZ8y',
  'artist_name': 'Jason Derulo',
  'external_url': 'https://api.spotify.com/v1/artists/07YZf4WDAMNwqr4jfgOZ8y'},
 {'artist_id': '1Cs0zKBU1kc0i8ypK3B9ai',
  'artist_name': 'David Guetta',
  'external_url': 'https://api.spotify.com/v1/artists/1Cs0zKBU1kc0i8ypK3B9ai'},
 {'artist_id': '0hCNtLu0JehylgoiP8L4Gh',
  'artist_name': 'Nicki Minaj',
  'external_url': 'https://api.spotify.com/v1/artists/0hCNtLu0JehylgoiP8L4Gh'},
 {'artist_id': '4RSyJzf7ef6Iu2rnLdabNq',
  'artist_name': 'Willy William',
  'external_url': 'https://api.spotify.com/v1/artists/4RSyJzf7ef6Iu2rnLdabNq'},
 {'artist_id': '7dGJo4pcD2V6oG8kP0tJRR',
  'artist_name': 'Eminem',
  'external_url': 'https://api.spotify.com/v1/artists/7dGJo4pcD2V6oG8kP0tJRR'},
 {'artist_id': '66CXWjxzNUsdJxJ2JdwvnR',
  'artist_name': 'Ariana Grande',
  'external_url': 'https://api.spotify.com/v1/artists/66CXWjxzNUsdJxJ2JdwvnR'},
 {'artist_id': '2qxJFvFYMEDqd7ui6kSAcq',
  'artist_name': 'Zedd',
  'external_url': 'https://api.spotify.com/v1/artists/2qxJFvFYMEDqd7ui6kSAcq'},
 {'artist_id': '67MNhiAICFY6Pwc2YxCO0K',
  'artist_name': 'Elley Duhé',
  'external_url': 'https://api.spotify.com/v1/artists/67MNhiAICFY6Pwc2YxCO0K'},
 {'artist_id': '246dkjvS1zLTtiykXe5h60',
  'artist_name': 'Post Malone',
  'external_url': 'https://api.spotify.com/v1/artists/246dkjvS1zLTtiykXe5h60'},
 {'artist_id': '1URnnhqYAYcrqrcwql10ft',
  'artist_name': '21 Savage',
  'external_url': 'https://api.spotify.com/v1/artists/1URnnhqYAYcrqrcwql10ft'},
 {'artist_id': '4obzFoKoKRHIphyHzJ35G3',
  'artist_name': 'Becky G',
  'external_url': 'https://api.spotify.com/v1/artists/4obzFoKoKRHIphyHzJ35G3'},
 {'artist_id': '1GDbiv3spRmZ1XdM1jQbT7',
  'artist_name': 'NATTI NATASHA',
  'external_url': 'https://api.spotify.com/v1/artists/1GDbiv3spRmZ1XdM1jQbT7'},
 {'artist_id': '66CXWjxzNUsdJxJ2JdwvnR',
  'artist_name': 'Ariana Grande',
  'external_url': 'https://api.spotify.com/v1/artists/66CXWjxzNUsdJxJ2JdwvnR'},
 {'artist_id': '7vk5e3vY1uw9plTHJAMwjN',
  'artist_name': 'Alan Walker',
  'external_url': 'https://api.spotify.com/v1/artists/7vk5e3vY1uw9plTHJAMwjN'},
 {'artist_id': '55fhWPvDiMpLnE4ZzNXZyW',
  'artist_name': 'Noah Cyrus',
  'external_url': 'https://api.spotify.com/v1/artists/55fhWPvDiMpLnE4ZzNXZyW'},
 {'artist_id': '5fyDppLDl1juIu1BcUT5zh',
  'artist_name': 'Digital Farm Animals',
  'external_url': 'https://api.spotify.com/v1/artists/5fyDppLDl1juIu1BcUT5zh'},
 {'artist_id': '4gvkdged3Xw3ImXFm3jiay',
  'artist_name': 'Juliander',
  'external_url': 'https://api.spotify.com/v1/artists/4gvkdged3Xw3ImXFm3jiay'},
 {'artist_id': '66CXWjxzNUsdJxJ2JdwvnR',
  'artist_name': 'Ariana Grande',
  'external_url': 'https://api.spotify.com/v1/artists/66CXWjxzNUsdJxJ2JdwvnR'},
 {'artist_id': '3Isy6kedDrgPYoTS1dazA9',
  'artist_name': 'Sean Paul',
  'external_url': 'https://api.spotify.com/v1/artists/3Isy6kedDrgPYoTS1dazA9'},
 {'artist_id': '1Cs0zKBU1kc0i8ypK3B9ai',
  'artist_name': 'David Guetta',
  'external_url': 'https://api.spotify.com/v1/artists/1Cs0zKBU1kc0i8ypK3B9ai'},
 {'artist_id': '4obzFoKoKRHIphyHzJ35G3',
  'artist_name': 'Becky G',
  'external_url': 'https://api.spotify.com/v1/artists/4obzFoKoKRHIphyHzJ35G3'},
 {'artist_id': '23fqKkggKUBHNkbKtXEls4',
  'artist_name': 'Kygo',
  'external_url': 'https://api.spotify.com/v1/artists/23fqKkggKUBHNkbKtXEls4'},
 {'artist_id': '360IAlyVv4PCEVjgyMZrxK',
  'artist_name': 'Miguel',
  'external_url': 'https://api.spotify.com/v1/artists/360IAlyVv4PCEVjgyMZrxK'},
 {'artist_id': '04gDigrS5kc9YWfZHwBETP',
  'artist_name': 'Maroon 5',
  'external_url': 'https://api.spotify.com/v1/artists/04gDigrS5kc9YWfZHwBETP'},
 {'artist_id': '4kYSro6naA4h99UJvo89HB',
  'artist_name': 'Cardi B',
  'external_url': 'https://api.spotify.com/v1/artists/4kYSro6naA4h99UJvo89HB'},
 {'artist_id': '1zNqDE7qDGCsyzJwohVaoX',
  'artist_name': 'Anne-Marie',
  'external_url': 'https://api.spotify.com/v1/artists/1zNqDE7qDGCsyzJwohVaoX'},
 {'artist_id': '0bdfiayQAKewqEvaU6rXCv',
  'artist_name': 'MØ',
  'external_url': 'https://api.spotify.com/v1/artists/0bdfiayQAKewqEvaU6rXCv'},
 {'artist_id': '5fMUXHkw8R8eOP2RNVYEZX',
  'artist_name': 'Diplo',
  'external_url': 'https://api.spotify.com/v1/artists/5fMUXHkw8R8eOP2RNVYEZX'},
 {'artist_id': '3EOEK57CV77D4ovYVcmiyt',
  'artist_name': 'Dennis Lloyd',
  'external_url': 'https://api.spotify.com/v1/artists/3EOEK57CV77D4ovYVcmiyt'},
 {'artist_id': '6LuN9FCkKOj5PcnpouEgny',
  'artist_name': 'Khalid',
  'external_url': 'https://api.spotify.com/v1/artists/6LuN9FCkKOj5PcnpouEgny'},
 {'artist_id': '2cWZOOzeOm4WmBJRnD5R7I',
  'artist_name': 'Normani',
  'external_url': 'https://api.spotify.com/v1/artists/2cWZOOzeOm4WmBJRnD5R7I'},
 {'artist_id': '1Cs0zKBU1kc0i8ypK3B9ai',
  'artist_name': 'David Guetta',
  'external_url': 'https://api.spotify.com/v1/artists/1Cs0zKBU1kc0i8ypK3B9ai'},
 {'artist_id': '1zNqDE7qDGCsyzJwohVaoX',
  'artist_name': 'Anne-Marie',
  'external_url': 'https://api.spotify.com/v1/artists/1zNqDE7qDGCsyzJwohVaoX'},
 {'artist_id': '4WN5naL3ofxrVBgFpguzKo',
  'artist_name': 'Rudimental',
  'external_url': 'https://api.spotify.com/v1/artists/4WN5naL3ofxrVBgFpguzKo'},
 {'artist_id': '4ScCswdRlyA23odg9thgIO',
  'artist_name': 'Jess Glynne',
  'external_url': 'https://api.spotify.com/v1/artists/4ScCswdRlyA23odg9thgIO'},
 {'artist_id': '3JhNCzhSMTxs9WLGJJxWOY',
  'artist_name': 'Macklemore',
  'external_url': 'https://api.spotify.com/v1/artists/3JhNCzhSMTxs9WLGJJxWOY'},
 {'artist_id': '2U3FuHYvL3vhkbDAXm24Ep',
  'artist_name': 'Dan Caplen',
  'external_url': 'https://api.spotify.com/v1/artists/2U3FuHYvL3vhkbDAXm24Ep'},
 {'artist_id': '39E15l8zeCDYpSZwFNX4G2',
  'artist_name': 'Eleni Foureira',
  'external_url': 'https://api.spotify.com/v1/artists/39E15l8zeCDYpSZwFNX4G2'},
 {'artist_id': '4AVFqumd2ogHFlRbKIjp1t',
  'artist_name': 'Alesso',
  'external_url': 'https://api.spotify.com/v1/artists/4AVFqumd2ogHFlRbKIjp1t'},
 {'artist_id': '7vk5e3vY1uw9plTHJAMwjN',
  'artist_name': 'Alan Walker',
  'external_url': 'https://api.spotify.com/v1/artists/7vk5e3vY1uw9plTHJAMwjN'},
 {'artist_id': '1eMmoIprPDWeFdB1FxU6ZV',
  'artist_name': 'Au/Ra',
  'external_url': 'https://api.spotify.com/v1/artists/1eMmoIprPDWeFdB1FxU6ZV'},
 {'artist_id': '6064pL9Hu3Wx2bwJMeOx6o',
  'artist_name': 'Tomine Harket',
  'external_url': 'https://api.spotify.com/v1/artists/6064pL9Hu3Wx2bwJMeOx6o'},
 {'artist_id': '4obzFoKoKRHIphyHzJ35G3',
  'artist_name': 'Becky G',
  'external_url': 'https://api.spotify.com/v1/artists/4obzFoKoKRHIphyHzJ35G3'},
 {'artist_id': '6vXTefBL93Dj5IqAWq6OTv',
  'artist_name': 'French Montana',
  'external_url': 'https://api.spotify.com/v1/artists/6vXTefBL93Dj5IqAWq6OTv'},
 {'artist_id': '329e4yvIujISKGKz1BZZbO',
  'artist_name': 'Farruko',
  'external_url': 'https://api.spotify.com/v1/artists/329e4yvIujISKGKz1BZZbO'},

In [214]:
song_list = []
for row in data['items']:
    song_id = row['track']['id']
    song_name = row['track']['name']
    song_duration = row['track']['duration_ms']
    song_url = row['track']['external_urls']['spotify']
    song_popularity = row['track']['popularity']
    song_added = row['added_at']
    album_id = row['track']['album']['id']
    artist_id = row['track']['album']['artists'][0]['id']
    song_element = {'song_id':song_id,'song_name':song_name,'duration_ms':song_duration,'url':song_url,
                    'popularity':song_popularity,'song_added':song_added,'album_id':album_id,
                    'artist_id':artist_id
                   }
    song_list.append(song_element)

In [216]:
album_df = pd.DataFrame.from_dict(album_list)

In [218]:
album_df.head()

,album_id,name,release_date,total_tracks,url
0,185Tm1g5U7eMOrm3m9SQUh,I Love It,2018-09-07,1,https://open.spotify.com/album/185Tm1g5U7eMOrm...
1,3HNnxK7NgLXbDoxRZxNWiR,Kamikaze,2018-08-31,13,https://open.spotify.com/album/3HNnxK7NgLXbDox...
2,1ATL5GLyefJaxhQzSPVrLX,Scorpion,2018-06-29,25,https://open.spotify.com/album/1ATL5GLyefJaxhQ...
3,7pkLXlFdpQDfmHujT2AbBK,Eastside (with Halsey & Khalid),2018-07-12,1,https://open.spotify.com/album/7pkLXlFdpQDfmHu...
4,78EicdHZr5XBWD7llEZ1Jh,Happier,2018-08-17,1,https://open.spotify.com/album/78EicdHZr5XBWD7...

In [220]:
album_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   album_id      100 non-null    object
 1   name          100 non-null    object
 2   release_date  100 non-null    object
 3   total_tracks  100 non-null    int64
 4   url           100 non-null    object
dtypes: int64(1), object(4)
memory usage: 4.0+ KB

In [83]:
album_df = album_df.drop_duplicates(subset=['album_id'])

In [87]:
artist_df = pd.DataFrame.from_dict(artist_list)

In [89]:
artist_df = artist_df.drop_duplicates(subset=['artist_id'])

In [230]:
#Song Dataframe
song_df = pd.DataFrame.from_dict(song_list)

In [232]:
song_df.head()

,song_id,song_name,duration_ms,url,popularity,song_added,album_id,artist_id
0,4S8d14HvHb70ImctNgVzQQ,I Love It (& Lil Pump),127946,https://open.spotify.com/track/4S8d14HvHb70Imc...,69,2018-09-20T16:07:04Z,185Tm1g5U7eMOrm3m9SQUh,5K4W6rqBFWDnAN6FQUkS6x
1,60SdxE8apGAxMiRrpbmLY0,Lucky You (feat. Joyner Lucas),244679,https://open.spotify.com/track/60SdxE8apGAxMiR...,70,2018-09-20T16:07:04Z,3HNnxK7NgLXbDoxRZxNWiR,7dGJo4pcD2V6oG8kP0tJRR
2,2G7V7zsVDxg1yRsu7Ew9RJ,In My Feelings,217925,https://open.spotify.com/track/2G7V7zsVDxg1yRs...,75,2018-09-20T16:07:04Z,1ATL5GLyefJaxhQzSPVrLX,3TVXtAsR1Inumwj472S9r4
3,0d2iYfpKoM0QCKvcLCkBao,Eastside (with Halsey & Khalid),173799,https://open.spotify.com/track/0d2iYfpKoM0QCKv...,73,2018-09-20T16:07:04Z,7pkLXlFdpQDfmHujT2AbBK,5CiGnKThu5ctn9pBxv7DGa
4,2dpaYNEQHiRxtZbfNsse99,Happier,214289,https://open.spotify.com/track/2dpaYNEQHiRxtZb...,9,2018-09-20T16:07:04Z,78EicdHZr5XBWD7llEZ1Jh,64KEffDW9EtZ1y2vBYgq8T

In [234]:
song_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   song_id      100 non-null    object
 1   song_name    100 non-null    object
 2   duration_ms  100 non-null    int64
 3   url          100 non-null    object
 4   popularity   100 non-null    int64
 5   song_added   100 non-null    object
 6   album_id     100 non-null    object
 7   artist_id    100 non-null    object
dtypes: int64(2), object(6)
memory usage: 6.4+ KB

In [93]:
artist_df.head()

,artist_id,artist_name,external_url
0,5YGY8feqx7naU7z4HrwZM6,Miley Cyrus,https://api.spotify.com/v1/artists/5YGY8feqx7n...
1,7tYKF4w9nC0nq9CsPZTHyP,SZA,https://api.spotify.com/v1/artists/7tYKF4w9nC0...
2,716NhGYqD1jl2wI1Qkgq36,Bizarrap,https://api.spotify.com/v1/artists/716NhGYqD1j...
3,0EmeFodog0BfCgMzAIvKQp,Shakira,https://api.spotify.com/v1/artists/0EmeFodog0B...
4,2wY79sveU1sp5g7SokKOiI,Sam Smith,https://api.spotify.com/v1/artists/2wY79sveU1s...

In [94]:
album_df.head()

,album_id,name,release_date,total_tracks,url
0,7I0tjwFtxUwBC1vgyeMAax,Flowers,2023-01-13,1,https://open.spotify.com/album/7I0tjwFtxUwBC1v...
1,1nrVofqDRs7cpWXJ49qTnP,SOS,2022-12-08,23,https://open.spotify.com/album/1nrVofqDRs7cpWX...
2,1gi2iwr1l8IUyHYHxi01pg,"Shakira: Bzrp Music Sessions, Vol. 53",2023-01-11,1,https://open.spotify.com/album/1gi2iwr1l8IUyHY...
3,3Uq1jNGnD412ZvCb6j2DKV,Gloria,2023-01-27,13,https://open.spotify.com/album/3Uq1jNGnD412ZvC...
4,7txGsnDSqVMoRl6RQ9XyZP,HEROES & VILLAINS,2022-12-02,15,https://open.spotify.com/album/7txGsnDSqVMoRl6...

In [224]:
album_df['release_date'] = pd.to_datetime(album_df['release_date'])

In [226]:
album_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   album_id      100 non-null    object
 1   name          100 non-null    object
 2   release_date  100 non-null    datetime64[ns]
 3   total_tracks  100 non-null    int64
 4   url           100 non-null    object
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 4.0+ KB

In [238]:
album_df.head()

,album_id,name,release_date,total_tracks,url
0,185Tm1g5U7eMOrm3m9SQUh,I Love It,2018-09-07,1,https://open.spotify.com/album/185Tm1g5U7eMOrm...
1,3HNnxK7NgLXbDoxRZxNWiR,Kamikaze,2018-08-31,13,https://open.spotify.com/album/3HNnxK7NgLXbDox...
2,1ATL5GLyefJaxhQzSPVrLX,Scorpion,2018-06-29,25,https://open.spotify.com/album/1ATL5GLyefJaxhQ...
3,7pkLXlFdpQDfmHujT2AbBK,Eastside (with Halsey & Khalid),2018-07-12,1,https://open.spotify.com/album/7pkLXlFdpQDfmHu...
4,78EicdHZr5XBWD7llEZ1Jh,Happier,2018-08-17,1,https://open.spotify.com/album/78EicdHZr5XBWD7...

In [98]:
song_df['song_added'] =  pd.to_datetime(song_df['song_added'])

In [100]:
song_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   song_id      50 non-null     object
 1   song_name    50 non-null     object
 2   duration_ms  50 non-null     int64
 3   url          50 non-null     object
 4   popularity   50 non-null     int64
 5   song_added   50 non-null     datetime64[ns, UTC]
 6   album_id     50 non-null     object
 7   artist_id    50 non-null     object
dtypes: datetime64[ns, UTC](1), int64(2), object(5)
memory usage: 3.2+ KB

In [236]:
song_df.head()

,song_id,song_name,duration_ms,url,popularity,song_added,album_id,artist_id
0,4S8d14HvHb70ImctNgVzQQ,I Love It (& Lil Pump),127946,https://open.spotify.com/track/4S8d14HvHb70Imc...,69,2018-09-20T16:07:04Z,185Tm1g5U7eMOrm3m9SQUh,5K4W6rqBFWDnAN6FQUkS6x
1,60SdxE8apGAxMiRrpbmLY0,Lucky You (feat. Joyner Lucas),244679,https://open.spotify.com/track/60SdxE8apGAxMiR...,70,2018-09-20T16:07:04Z,3HNnxK7NgLXbDoxRZxNWiR,7dGJo4pcD2V6oG8kP0tJRR
2,2G7V7zsVDxg1yRsu7Ew9RJ,In My Feelings,217925,https://open.spotify.com/track/2G7V7zsVDxg1yRs...,75,2018-09-20T16:07:04Z,1ATL5GLyefJaxhQzSPVrLX,3TVXtAsR1Inumwj472S9r4
3,0d2iYfpKoM0QCKvcLCkBao,Eastside (with Halsey & Khalid),173799,https://open.spotify.com/track/0d2iYfpKoM0QCKv...,73,2018-09-20T16:07:04Z,7pkLXlFdpQDfmHujT2AbBK,5CiGnKThu5ctn9pBxv7DGa
4,2dpaYNEQHiRxtZbfNsse99,Happier,214289,https://open.spotify.com/track/2dpaYNEQHiRxtZb...,9,2018-09-20T16:07:04Z,78EicdHZr5XBWD7llEZ1Jh,64KEffDW9EtZ1y2vBYgq8T

3.11.7 (main, Dec 15 2023, 12:09:04) [Clang 14.0.6 ]